# Generated by Django 5.2.7 on 2025-11-24 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience_manager', '0003_audiencecontact_expiry_date'),
        ('email_provider', '0001_initial'),
        ('templates', '0008_template_usage_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_type', models.CharField(choices=[('promotional', 'Promotional'), ('renewal', 'Renewal'), ('welcome', 'Welcome')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('scheduled', 'Scheduled')], default='draft', max_length=10)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_whatsapp', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cm_campaigns', to='audience_manager.audience')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_deleted_campaigns', to=settings.AUTH_USER_MODEL)),
                ('email_provider', models.ForeignKey(blank=True, help_text='Specific provider for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_provider.emailproviderconfig')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_updated_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Manager Campaign',
                'verbose_name_plural': 'Campaign Manager Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('step_order', models.PositiveIntegerField()),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('delay_weeks', models.PositiveIntegerField(default=0)),
                ('trigger_condition', models.CharField(choices=[('always', 'Always Send'), ('no_response', 'Send if no response'), ('no_action', 'Send if no action taken')], default='always', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_sequence_steps', to='campaign_manager.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_created_steps', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_deleted_steps', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_updated_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Manager Step',
                'verbose_name_plural': 'Campaign Manager Steps',
                'ordering': ['campaign', 'step_order'],
                'unique_together': {('campaign', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_pending_tasks', to='campaign_manager.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_pending_tasks', to='audience_manager.audiencecontact')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_pending_tasks', to='campaign_manager.sequencestep')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('replied', 'Replied'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('message_provider_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_logs', to='campaign_manager.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_logs', to='audience_manager.audiencecontact')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_logs', to='campaign_manager.sequencestep')),
            ],
            options={
                'verbose_name': 'Campaign Manager Log',
                'verbose_name_plural': 'Campaign Manager Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
