# Generated by Django 5.2.7 on 2025-12-10 09:51
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
        ('sms_provider', '0001_initial'),
        ('whatsapp_provider', '0017_whatsappmessagetemplate_provider_and_more'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sms_provider',
            field=models.ForeignKey(blank=True, help_text='Select specific SMS credentials (MSG91/Twilio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_provider.smsprovider'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_provider',
            field=models.ForeignKey(blank=True, help_text='Select specific WhatsApp credentials (Meta/Twilio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=('whatsapp_provider.whatsappprovider')),
        ),
    ]
