# Generated by Django 5.2.7 on 2025-12-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0002_campaign_sms_provider_campaign_whatsapp_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='email_provider',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sms_provider',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='whatsapp_provider',
        ),
    ]
