# Generated by Django 5.2.7 on 2025-12-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0003_remove_campaign_email_provider_and_more'),
        ('email_provider', '0003_alter_emailprovidertestresult_options_and_more'),
        ('sms_provider', '0001_initial'),
        ('whatsapp_provider', '0024_add_missing_related_provider_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_provider',
            field=models.ForeignKey(blank=True, help_text='Specific provider for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_provider.emailproviderconfig'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_provider',
            field=models.ForeignKey(blank=True, help_text='Select specific SMS credentials (MSG91/Twilio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_provider.smsprovider'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_provider',
            field=models.ForeignKey(blank=True, help_text='Select specific WhatsApp credentials (Meta/Twilio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_provider.whatsappprovider'),
        ),
    ]
