# Generated by Django 4.2.7 on 2025-08-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0002_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('insight_type', models.CharField(choices=[('claim_likelihood', 'Claim Likelihood'), ('customer_profile', 'Customer Profile'), ('renewal_prediction', 'Renewal Prediction'), ('risk_assessment', 'Risk Assessment'), ('behavior_analysis', 'Behavior Analysis'), ('payment_pattern', 'Payment Pattern')], db_index=True, help_text='Type of AI insight', max_length=50)),
                ('insight_title', models.CharField(help_text="Title of the insight (e.g., 'Claim Likelihood', 'Customer Profile')", max_length=200)),
                ('insight_value', models.CharField(help_text="Value or result of the insight (e.g., 'Moderate', 'Good', 'High Risk')", max_length=100)),
                ('insight_description', models.TextField(help_text='Detailed explanation of the insight')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='AI confidence level (0.0000 to 1.0000)', max_digits=5, null=True)),
                ('key_observations', models.JSONField(default=dict, help_text='Structured data for key observations and metrics')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this insight was generated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this insight should be displayed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this insight is about', on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, help_text='Policy this insight is about (optional for customer-level insights)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at', 'insight_type'],
            },
        ),
        migrations.CreateModel(
            name='AIInsightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('previous_value', models.CharField(help_text='Previous insight value', max_length=100)),
                ('new_value', models.CharField(help_text='New insight value', max_length=100)),
                ('previous_confidence', models.DecimalField(blank=True, decimal_places=4, help_text='Previous confidence score', max_digits=5, null=True)),
                ('new_confidence', models.DecimalField(blank=True, decimal_places=4, help_text='New confidence score', max_digits=5, null=True)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for the change in insight')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When this change occurred')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('insight', models.ForeignKey(help_text='The insight this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ai_insights.aiinsight')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_insights_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['customer', 'insight_type'], name='ai_insights_custome_c9309e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['policy', 'insight_type'], name='ai_insights_policy__cf09b5_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['generated_at'], name='ai_insights_generat_55fbee_idx'),
        ),
    ]
