# Generated by Django 4.2.7 on 2025-10-13 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(help_text='Unique session identifier for this conversation', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Conversation title (auto-generated from first message)', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', help_text='Current status of the conversation', max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data for the conversation')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When this conversation was started')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Total number of messages in this conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who initiated this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('analytics_type', models.CharField(choices=[('dashboard_summary', 'Dashboard Summary'), ('renewal_analysis', 'Renewal Analysis'), ('customer_insights', 'Customer Insights'), ('campaign_performance', 'Campaign Performance'), ('payment_analysis', 'Payment Analysis'), ('predictive_insights', 'Predictive Insights')], db_index=True, help_text='Type of analytics generated', max_length=50)),
                ('title', models.CharField(help_text='Title of the analytics report', max_length=200)),
                ('summary', models.TextField(help_text='Summary of the analytics findings')),
                ('detailed_analysis', models.JSONField(default=dict, help_text='Detailed analysis data and metrics')),
                ('insights', models.JSONField(default=list, help_text='List of key insights generated')),
                ('recommendations', models.JSONField(default=list, help_text='List of actionable recommendations')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='AI confidence level (0.0000 to 1.0000)', max_digits=5, null=True)),
                ('data_snapshot', models.JSONField(default=dict, help_text='Snapshot of data used for analysis')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this analysis was generated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this analysis is still relevant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who requested this analysis', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_analytics',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], db_index=True, help_text='Role of the message sender', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (tokens used, model, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this message was sent')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether this message has been edited')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_insights.aiconversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='ai_messages_convers_0c5386_idx'), models.Index(fields=['role', 'timestamp'], name='ai_messages_role_03f68d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'status'], name='ai_conversa_user_id_59068a_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['session_id'], name='ai_conversa_session_687709_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['last_activity'], name='ai_conversa_last_ac_fe10eb_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalytics',
            index=models.Index(fields=['user', 'analytics_type'], name='ai_analytic_user_id_2be20a_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalytics',
            index=models.Index(fields=['analytics_type', 'generated_at'], name='ai_analytic_analyti_34e2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalytics',
            index=models.Index(fields=['generated_at'], name='ai_analytic_generat_71e8ff_idx'),
        ),
    ]
