# Generated by Django 4.2.7 on 2025-10-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLogsChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Unique identifier for the case', max_length=100, unique=True)),
                ('policy_id', models.CharField(help_text='Policy ID associated with the case', max_length=100)),
                ('customer_id', models.CharField(help_text='Customer ID associated with the case', max_length=100)),
                ('case_type', models.CharField(help_text='Type of case (Renewal, Claim, etc.)', max_length=50)),
                ('case_status', models.CharField(help_text='Current status of the case', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', help_text='Priority level of the case', max_length=20)),
                ('chatbot_session_id', models.CharField(help_text='Unique session ID for chatbot interaction', max_length=255, unique=True)),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last time customer interacted with chatbot')),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Number of interactions with chatbot')),
                ('is_active', models.BooleanField(default=True, help_text='Whether chatbot is active for this case')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Logs Chatbot',
                'verbose_name_plural': 'Case Logs Chatbots',
                'db_table': 'case_logs_chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseLogsChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], help_text='Type of message', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on message helpfulness', null=True)),
                ('chatbot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='case_logs_chatbot.caselogschatbot')),
            ],
            options={
                'verbose_name': 'Case Logs Chatbot Message',
                'verbose_name_plural': 'Case Logs Chatbot Messages',
                'db_table': 'case_logs_chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
