# Generated by Django 5.2.7 on 2025-12-01 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_role_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModuleSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imap_connection_status', models.BooleanField(default=False, help_text='Status of the main IMAP test connection.')),
                ('enable_webhook_notifications', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('enable_mail_merge', models.BooleanField(default=False)),
                ('document_storage_path', models.CharField(default='/documents/templates', max_length=255)),
                ('output_directory', models.CharField(default='/documents/generated', max_length=255)),
                ('email_polling_interval_minutes', models.IntegerField(choices=[(1, '1 Minute'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=5)),
                ('auto_categorization_enabled', models.BooleanField(default=True)),
                ('fallback_tagging_enabled', models.BooleanField(default=True)),
                ('emails_per_page', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('auto_refresh_inbox', models.BooleanField(default=True)),
                ('mark_read_on_open', models.BooleanField(default=True)),
                ('ai_intent_classification', models.BooleanField(default=True)),
                ('ai_sentiment_analysis', models.BooleanField(default=True)),
                ('ai_realtime_collaboration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_module_settings', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_email_module_settings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_module_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Module Settings',
                'verbose_name_plural': 'Email Module Settings',
                'db_table': 'email_module_settings',
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword to match in email subject or content.', max_length=100)),
                ('category', models.CharField(choices=[('refund', 'Refund'), ('complaint', 'Complaint'), ('appointment', 'Appointment'), ('feedback', 'Feedback'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable this classification rule.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classification_rules', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_classification_rules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_classification_rules', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classification Rule',
                'verbose_name_plural': 'Classification Rules',
                'db_table': 'email_settings_classification_rules',
                'unique_together': {('user', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="A friendly name for the account (e.g., 'Support Inbox').", max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('email_provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365'), ('yahoo', 'Yahoo Mail'), ('custom', 'Custom IMAP/SMTP')], default='gmail', max_length=50)),
                ('imap_server', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=993, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_server', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('use_ssl_tls', models.BooleanField(default=True, help_text='Use SSL/TLS encryption for connections.')),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(choices=[(1, '1 Minute'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_credential', models.CharField(help_text='The encrypted App Password or OAuth Token provided by the email service for connection.', max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_accounts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_email_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The owner of this configuration.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'db_table': 'email_settings_accounts',
                'unique_together': {('user', 'email_address')},
            },
        ),
    ]
