# Generated by Django 5.2.7 on 2025-12-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='connection_status',
            field=models.BooleanField(default=False, help_text='True if the last connection test was successful.'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync or test.', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_sync_log',
            field=models.TextField(blank=True, help_text='Stores the error message if the connection failed.'),
        ),
    ]
