# Generated by Django 5.2.7 on 2025-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_settings', '0002_emailaccount_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodulesettings',
            name='attach_to_emails',
            field=models.BooleanField(default=True, help_text='Automatically attach generated documents to emails'),
        ),
        migrations.AddField(
            model_name='emailmodulesettings',
            name='auto_generate_documents',
            field=models.BooleanField(default=False, help_text='Automatically create documents during bulk email campaigns'),
        ),
    ]
