# Generated by Django 5.2.7 on 2025-12-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_settings', '0003_emailmodulesettings_attach_to_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique ID from the email provider to prevent duplicates.', max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=998)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('folder', models.CharField(default='INBOX', max_length=50)),
                ('category', models.CharField(choices=[('refund', 'Refund'), ('complaint', 'Complaint'), ('appointment', 'Appointment'), ('feedback', 'Feedback'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_processed', models.BooleanField(default=False, help_text='True if AI/Rules have already run on this email.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_settings.emailaccount')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['message_id'], name='email_setti_message_4b39c2_idx'), models.Index(fields=['email_account', 'received_at'], name='email_setti_email_a_1d90cc_idx')],
            },
        ),
    ]
