# Generated by Django 5.2.7 on 2025-12-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0001_initial'),
        ('email_settings', '0004_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_default_sender',
            field=models.BooleanField(default=False, help_text="If true, this account is pre-selected as the 'From' address in new campaigns."),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sending_method',
            field=models.CharField(choices=[('smtp', 'Use Incoming SMTP Credentials (Gmail/Outlook)'), ('system_default', 'Use System Default Provider (e.g. Corp SendGrid)'), ('specific_provider', 'Use Specific Provider (Override)')], default='smtp', help_text='Determines how emails are sent from this account.', max_length=20),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='specific_provider',
            field=models.ForeignKey(blank=True, help_text="If 'Use Specific Provider' is selected, this provider (e.g. Marketing SendGrid) will be used.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_provider.emailproviderconfig'),
        ),
    ]
