# Generated by Django 5.2.7 on 2025-12-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0001_initial'),
        ('email_settings', '0005_emailaccount_is_default_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='specific_provider',
            field=models.ForeignKey(blank=True, help_text="If 'Use Specific Provider' is selected, this provider will be used.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_provider.emailproviderconfig'),
        ),
    ]
