# Generated by Django 5.2.6 on 2025-09-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text="Offer title (e.g., 'EMI Payment Plan', 'Annual Payment')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the offer')),
                ('offer_type', models.CharField(choices=[('payment_option', 'Payment Option'), ('product', 'Product'), ('bundle', 'Bundle'), ('funding', 'Funding'), ('discount', 'Discount'), ('special_offer', 'Special Offer')], help_text='Type of offer (payment_option, product, bundle, etc.)', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount for payment plans (e.g., 1542 for EMI)', max_digits=15, null=True)),
                ('discount', models.CharField(blank=True, help_text="Discount percentage or amount (e.g., '5%', '2% discount')", max_length=50, null=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', help_text='Currency for the amount', max_length=3)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate for funding options (e.g., 3.5 for 3.5% p.a.)', max_digits=5, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of features/benefits (e.g., ['No additional charges', 'Flexible payment schedule'])")),
                ('extra_info', models.JSONField(blank=True, default=dict, help_text='Additional information as JSON (e.g., terms, conditions, special notes)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offer is currently active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying offers (lower numbers appear first)')),
                ('icon', models.CharField(blank=True, help_text='Icon name or class for frontend display', max_length=100, null=True)),
                ('color_scheme', models.CharField(blank=True, help_text="Color scheme for frontend display (e.g., 'blue', 'green', 'orange')", max_length=50, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions for this offer', null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='When this offer becomes active', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When this offer expires', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['offer_type', 'is_active'], name='offers_offer_t_135d28_idx'), models.Index(fields=['is_active', 'display_order'], name='offers_is_acti_aeebea_idx'), models.Index(fields=['start_date', 'end_date'], name='offers_start_d_3f9be3_idx')],
            },
        ),
    ]
