# Generated by Django 4.2.7 on 2025-08-12 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exclusion_type', models.CharField(choices=[('not_covered', 'Not Covered'), ('conditions_apply', 'Conditions Apply'), ('partial_coverage', 'Partial Coverage'), ('waiting_period', 'Waiting Period'), ('geographical_limit', 'Geographical Limit'), ('age_limit', 'Age Limit'), ('pre_existing_condition', 'Pre-existing Condition'), ('activity_exclusion', 'Activity Exclusion'), ('other', 'Other')], db_index=True, default='not_covered', help_text='Type of exclusion — e.g., not_covered or conditions_apply', max_length=50)),
                ('description', models.TextField(help_text='The actual exclusion text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Links this exclusion to a specific policy', on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_exclusions',
                'ordering': ['policy', 'exclusion_type', 'id'],
                'indexes': [models.Index(fields=['policy', 'exclusion_type'], name='policy_excl_policy__0c17fc_idx'), models.Index(fields=['exclusion_type'], name='policy_excl_exclusi_bbb669_idx'), models.Index(fields=['policy'], name='policy_excl_policy__f4374d_idx')],
            },
        ),
    ]
