# Generated by Django 4.2.7 on 2025-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_exclusions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyexclusion',
            name='description',
            field=models.TextField(blank=True, help_text='The actual exclusion text'),
        ),
    ]
