# Generated by Django 5.2.7 on 2025-11-05 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_customers_cu_channel_123abc_idx_customers_c_channel_d1da5f_idx'),
        ('policies', '0009_claimtimelineevent'),
        ('policy_timeline', '0002_policytimelinefilter_customertimelinesummary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_payments_last_12_months', models.PositiveSmallIntegerField(default=0, help_text='Total expected payments in the last 12 months')),
                ('on_time_payments_last_12_months', models.PositiveSmallIntegerField(default=0, help_text='Number of on-time payments in the last 12 months')),
                ('total_paid_last_12_months', models.DecimalField(decimal_places=2, default=0, help_text='Total premium amount paid in the last 12 months', max_digits=12)),
                ('average_payment_timing_days', models.SmallIntegerField(default=0, help_text='Average payment timing (e.g., 5 days early)')),
                ('preferred_payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('auto_debit', 'Auto-Debit'), ('manual', 'Manual Payment')], default='auto_debit', help_text="Customer's preferred payment method for premium", max_length=20)),
                ('late_payment_instances', models.PositiveSmallIntegerField(default=0, help_text='Number of late payment instances')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(help_text='Customer this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_payment_schedule',
            },
        ),
        migrations.CreateModel(
            name='UpcomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(help_text='Date the payment is due')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount of the premium payment due', max_digits=12)),
                ('days_to_due', models.SmallIntegerField(help_text='Calculated days remaining until due date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Related customer', on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_payments', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Related policy', on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_payments', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upcoming_payments',
                'ordering': ['due_date'],
            },
        ),
    ]
