# Generated by Django 4.2.7 on 2025-09-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='communication_preferences',
        ),
    ]
