# Generated by Django 4.2.7 on 2025-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_communication_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the email has been verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when email was verified', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN number for verification', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the PAN number has been verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when PAN was verified', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the phone number has been verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when phone was verified', null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email_verified'], name='customers_c_email_v_39586d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_verified'], name='customers_c_phone_v_8f8b46_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pan_verified'], name='customers_c_pan_ver_506e32_idx'),
        ),
    ]
