# Generated by Django 5.2.6 on 2025-11-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_channel_id_to_customer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_channel_d1da5f_idx',
            old_name='customers_cu_channel_123abc_idx',
        ),
    ]
