# Generated by Django 5.2.7 on 2025-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_customers_cu_channel_123abc_idx_customers_c_channel_d1da5f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
