# Generated by Django 5.2.6 on 2025-11-08 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0007_template_is_dlt_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('to', models.EmailField(help_text='Primary recipient email address', max_length=255)),
                ('cc', models.TextField(blank=True, help_text='CC recipient email addresses (comma-separated, optional)', null=True)),
                ('bcc', models.TextField(blank=True, help_text='BCC recipient email addresses (comma-separated, optional)', null=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('message', models.TextField(help_text='Email message body content')),
                ('policy_number', models.CharField(blank=True, help_text='Associated policy number', max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name', max_length=200, null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='Policy renewal date', null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Premium amount', max_digits=15, null=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Normal', help_text='Email priority level', max_length=20)),
                ('schedule_send', models.BooleanField(default=False, help_text='Whether to schedule the email for later sending')),
                ('schedule_date_time', models.DateTimeField(blank=True, help_text='Scheduled date and time for sending the email', null=True)),
                ('track_opens', models.BooleanField(default=False, help_text='Whether to track email opens')),
                ('track_clicks', models.BooleanField(default=False, help_text='Whether to track email link clicks')),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='pending', help_text='Status of the email', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Date and time when email was sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if email sending failed', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('templates_id', models.ForeignKey(blank=True, db_column='templates_id', help_text='Associated template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_managers', to='templates.template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_manager',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to'], name='email_manag_to_bf750b_idx'), models.Index(fields=['policy_number'], name='email_manag_policy__0bbd66_idx'), models.Index(fields=['priority'], name='email_manag_priorit_cf4827_idx'), models.Index(fields=['schedule_send', 'schedule_date_time'], name='email_manag_schedul_5bd57b_idx'), models.Index(fields=['email_status'], name='email_manag_email_s_a3103b_idx'), models.Index(fields=['templates_id'], name='email_manag_templat_fa668a_idx'), models.Index(fields=['created_at'], name='email_manag_created_fc8838_idx')],
            },
        ),
    ]
