# Generated by Django 5.2.6 on 2025-11-10 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
        ('templates', '0007_template_is_dlt_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailmanager',
            name='email_manag_templat_fa668a_idx',
        ),
        migrations.RenameField(
            model_name='emailmanager',
            old_name='templates_id',
            new_name='template',
        ),
        migrations.AddIndex(
            model_name='emailmanager',
            index=models.Index(fields=['template'], name='email_manag_templat_fa668a_idx'),
        ),
    ]
