# Generated by Django 5.2.6 on 2025-11-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0002_remove_emailmanager_email_manag_templat_fa668a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanager',
            name='started',
            field=models.BooleanField(default=False, help_text='Indicates whether the email sending process has started'),
        ),
    ]
