# Generated by Django 5.2.6 on 2025-11-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0003_emailmanager_started'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManagerInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=255)),
                ('to_email', models.TextField(help_text='Recipient email addresses (comma separated)')),
                ('subject', models.CharField(blank=True, help_text='Email subject', max_length=500, null=True)),
                ('message', models.TextField(blank=True, help_text='Plain text email body', null=True)),
                ('html_message', models.TextField(blank=True, help_text='HTML version of email body if available', null=True)),
                ('received_at', models.DateTimeField(help_text='Time when the email was received on the server')),
                ('message_id', models.CharField(help_text='Unique message ID from email header', max_length=255, unique=True)),
                ('in_reply_to', models.CharField(blank=True, help_text='Message-ID of the email this is replying to', max_length=255, null=True)),
                ('references', models.TextField(blank=True, help_text='Thread reference IDs', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Marks whether this email has been read')),
                ('attachments', models.JSONField(blank=True, help_text='Stores metadata of attachments (name, size, path)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('related_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_replies', to='email_manager.emailmanager')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_manager_inbox',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['from_email'], name='email_manag_from_em_258e35_idx'), models.Index(fields=['to_email'], name='email_manag_to_emai_e344c6_idx'), models.Index(fields=['received_at'], name='email_manag_receive_aa485f_idx')],
            },
        ),
    ]
