# Generated by Django 5.2.6 on 2025-11-11 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0004_emailmanagerinbox'),
        ('templates', '0007_template_is_dlt_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanager',
            name='message_id',
            field=models.CharField(blank=True, help_text='Unique message ID of the sent email', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='emailmanager',
            index=models.Index(fields=['message_id'], name='email_manag_message_9508be_idx'),
        ),
    ]
