# Generated by Django 5.2.6 on 2025-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0006_emailreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanager',
            name='from_email',
            field=models.EmailField(blank=True, help_text='From email address used to send this email', max_length=255, null=True),
        ),
    ]
