# Generated by Django 5.2.6 on 2025-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0007_emailmanager_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanagerinbox',
            name='started',
            field=models.BooleanField(default=False, help_text='Indicates whether processing for this inbox email has started'),
        ),
    ]
