# Generated by Django 5.2.6 on 2025-11-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0009_startedreplymail'),
        ('templates', '0008_template_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='startedreplymail',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='schedule_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='schedule_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.template'),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='track_clicks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startedreplymail',
            name='track_opens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='startedreplymail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startedreplymail',
            name='to_email',
            field=models.TextField(),
        ),
    ]
