# Generated by Django 5.2.6 on 2025-11-25 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0011_emailmanagerforwardmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanagerforwardmail',
            name='original_email_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_from_manager', to='email_manager.emailmanager'),
        ),
    ]
