# Generated by Django 4.2.7 on 2025-10-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTimelineChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='Unique identifier for the customer', max_length=100, unique=True)),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=255)),
                ('policy_id', models.CharField(help_text='Policy ID associated with the timeline', max_length=100)),
                ('policy_type', models.CharField(help_text='Type of policy (Life, Motor, Health, etc.)', max_length=100)),
                ('policy_premium', models.DecimalField(decimal_places=2, help_text='Current policy premium', max_digits=10)),
                ('policy_start_date', models.DateField(help_text='Policy start date')),
                ('policy_age', models.PositiveIntegerField(help_text='Policy age in years')),
                ('chatbot_session_id', models.CharField(help_text='Unique session ID for chatbot interaction', max_length=255, unique=True)),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last time customer interacted with chatbot')),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Number of interactions with chatbot')),
                ('is_active', models.BooleanField(default=True, help_text='Whether chatbot is active for this policy timeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Timeline Chatbot',
                'verbose_name_plural': 'Policy Timeline Chatbots',
                'db_table': 'policy_timeline_chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTimelineChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], help_text='Type of message', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on message helpfulness', null=True)),
                ('chatbot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='policytimeline_chatbot.policytimelinechatbot')),
            ],
            options={
                'verbose_name': 'Policy Timeline Chatbot Message',
                'verbose_name_plural': 'Policy Timeline Chatbot Messages',
                'db_table': 'policy_timeline_chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
