# Generated by Django 4.2.7 on 2025-08-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('residence_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('bungalow', 'Bungalow'), ('flat', 'Flat'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('other', 'Other')], help_text='Type of residence', max_length=50)),
                ('residence_status', models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('leased', 'Leased'), ('family_owned', 'Family Owned'), ('company_provided', 'Company Provided'), ('other', 'Other')], help_text='Ownership status of residence', max_length=50)),
                ('residence_location', models.CharField(blank=True, help_text='Location/address of residence', max_length=200)),
                ('residence_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average'), ('poor', 'Poor')], help_text='Quality/condition rating of residence', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who owns these assets', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_as_custome_c2e97a_idx'), models.Index(fields=['residence_type'], name='customer_as_residen_3e38a6_idx'), models.Index(fields=['residence_status'], name='customer_as_residen_f90376_idx'), models.Index(fields=['residence_rating'], name='customer_as_residen_6a5b57_idx')],
            },
        ),
    ]
