# Generated by Django 5.2.7 on 2025-11-24 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('files_upload', '0003_alter_fileupload_uploaded_file'),
        ('sms_provider', '0001_initial'),
        ('target_audience', '0001_initial'),
        ('templates', '0008_template_usage_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sms_provider',
            field=models.ForeignKey(blank=True, help_text='Specific provider for SMS channel. If null, uses system default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaigns', to='sms_provider.smsprovider'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='target_audience.targetaudience'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='templates.template'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='files_upload.fileupload'),
        ),
    ]
