# Generated by Django 5.2.7 on 2025-11-24 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_initial'),
        ('customers', '0006_rename_customers_cu_channel_123abc_idx_customers_c_channel_d1da5f_idx'),
        ('policies', '0009_claimtimelineevent'),
        ('templates', '0008_template_usage_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


    operations = [
        migrations.AddField(
            model_name='campaignanalytics',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignautomation',
            name='campaign_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignautomation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignautomation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignautomation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignfeedback',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignfeedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='campaignfeedback',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignfeedback',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignfeedback',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignscheduleinterval',
            name='campaign',
            field=models.ForeignKey(help_text='Campaign this schedule interval belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_intervals', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignscheduleinterval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignscheduleinterval',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignscheduleinterval',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template to use for this interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedules', to='templates.template'),
        ),
        migrations.AddField(
            model_name='campaignscheduleinterval',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignsegment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignsegment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.campaigntype'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'email_status'], name='campaign_re_campaig_2298f4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'whatsapp_status'], name='campaign_re_campaig_6f6740_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'sms_status'], name='campaign_re_campaig_684ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'has_responded'], name='campaign_re_campaig_a2b399_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'conversion_achieved'], name='campaign_re_campaig_6b7b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['email_status', 'email_sent_at'], name='campaign_re_email_s_3343b2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['customer', 'campaign'], name='campaign_re_custome_6ee88c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['response_type', 'response_received_at'], name='campaign_re_respons_71383e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'customer')},
        ),
        migrations.AddIndex(
            model_name='campaignscheduleinterval',
            index=models.Index(fields=['campaign', 'sequence_order'], name='campaign_sc_campaig_074f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignscheduleinterval',
            index=models.Index(fields=['scheduled_at'], name='campaign_sc_schedul_433a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignscheduleinterval',
            index=models.Index(fields=['is_active', 'is_sent'], name='campaign_sc_is_acti_f3f528_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignscheduleinterval',
            constraint=models.UniqueConstraint(fields=('campaign', 'sequence_order'), name='unique_campaign_sequence_order'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'started_at'], name='campaigns_status_5db58a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'status'], name='campaigns_campaig_849637_idx'),
        ),
    ]
