# Generated by Django 5.2.7 on 2025-12-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_initial'),
        ('whatsapp_provider', '0017_whatsappmessagetemplate_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_provider',
            field=models.ForeignKey(blank=True, help_text='Specific provider for WhatsApp channel. If null, uses system default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to='whatsapp_provider.whatsappprovider'),
        ),
    ]
