# Generated by Django 5.2.7 on 2025-12-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('download_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_invoice',
            },
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'billing_period',
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PlatformCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(default='Monthly', max_length=20)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_charges', to='billing.billingperiod')),
            ],
        ),
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('email', 'Email Notifications'), ('sms', 'SMS Notifications'), ('api', 'API Calls'), ('whatsapp', 'WhatsApp Business API')], max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_charges', to='billing.billingperiod')),
            ],
            options={
                'db_table': 'usage_charge',
            },
        ),
    ]
