# Generated by Django 5.2.7 on 2025-12-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usagecharge',
            table='billing_usage_charge',
        ),
    ]
