# Generated by Django 5.2.7 on 2025-12-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_usagecharge_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('email', 'Email Notifications'), ('sms', 'SMS Notifications'), ('api', 'API Calls'), ('whatsapp', 'WhatsApp Business API')], max_length=50)),
                ('total_recipients', models.IntegerField()),
                ('successful_deliveries', models.IntegerField()),
                ('failed_deliveries', models.IntegerField()),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'billing_campaign',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('email', 'Email Notifications'), ('sms', 'SMS Notifications'), ('api', 'API Calls'), ('whatsapp', 'WhatsApp Business API')], max_length=50)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'billing_vendor',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('email', 'Email Notifications'), ('sms', 'SMS Notifications'), ('api', 'API Calls'), ('whatsapp', 'WhatsApp Business API')], max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('message_snippet', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=6)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.vendor')),
            ],
            options={
                'db_table': 'billing_communication',
                'ordering': ['-timestamp'],
            },
        ),
    ]
