# Generated by Django 5.2.7 on 2025-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_campaign_vendor_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cost_per_message',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(default='VEN001', max_length=20),
        ),
    ]
