# Generated by Django 5.2.7 on 2025-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_vendor_cost_per_message_vendor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
