# Generated by Django 5.2.7 on 2025-12-27 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_vendor_service_type_alter_vendor_vendor_id'),
        ('customers', '0007_customer_document_language_and_more'),
        ('renewals', '0033_merge_20251219_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_logs', to='renewals.renewalcase'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_logs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
