# Generated by Django 5.2.7 on 2025-12-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_communicationlog_attempts_communicationlog_case_and_more'),
        ('policytimeline_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='policy_chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_logs', to='policytimeline_chatbot.policytimelinechatbot'),
        ),
    ]
