# Generated by Django 5.2.7 on 2025-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_communicationlog_policy_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
