# Generated by Django 4.2.7 on 2025-09-16 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('marketing', 'Marketing'), ('notification', 'Notification'), ('reminder', 'Reminder'), ('confirmation', 'Confirmation'), ('welcome', 'Welcome'), ('renewal', 'Renewal'), ('payment', 'Payment')], default='general', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Used for email subject', max_length=200)),
                ('content', models.TextField(help_text='Template body content (HTML or plain text)')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of dynamic variables used in the template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'channel')},
            },
        ),
    ]
