# Generated by Django 4.2.7 on 2025-09-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        # 1️⃣ Add the column first
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(
                max_length=50,
                default='html',
            ),
        ),

        # 2️⃣ Ensure existing rows are updated (safe)
        migrations.RunSQL(
            "UPDATE templates SET template_type = 'html' WHERE template_type IS NULL;",
            reverse_sql="UPDATE templates SET template_type = NULL WHERE template_type = 'html';"
        ),
    ]
