# Generated by Django 5.2.6 on 2025-09-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('html', 'HTML'), ('text', 'Text'), ('markdown', 'Markdown')], default='html', max_length=20),
        ),
    ]
