# Generated by Django 4.2.7 on 2025-09-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_template_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20),
        ),
    ]
