# Generated by Django 4.2.7 on 2025-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_fix_template_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='dlt_template_id',
            field=models.CharField(blank=True, help_text='Required for SMS and WhatsApp templates', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of assigned tags for quick filtering'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('promotional', 'Promotional'), ('transactional', 'Transactional'), ('renewal', 'Renewal'), ('welcome', 'Welcome'), ('payment', 'Payment'), ('claims', 'Claims'), ('remainder', 'Remainder')], default='promotional', max_length=20),
        ),
    ]
