# Generated by Django 4.2.7 on 2025-10-31 11:26

from django.db import migrations


def forwards(apps, schema_editor):
    Template = apps.get_model('templates', 'Template')

    mapping = {
        'general': 'promotional',
        'marketing': 'promotional',
        'notification': 'transactional',
        'reminder': 'remainder',
        'confirmation': 'transactional',
        'welcome': 'welcome',
        'renewal': 'renewal',
        'payment': 'payment',
    }

    for old_value, new_value in mapping.items():
        Template.objects.filter(category=old_value).update(category=new_value)

    # Any remaining legacy values fallback to promotional
    valid_values = {
        'promotional', 'transactional', 'renewal', 'welcome', 'payment', 'claims', 'remainder'
    }
    Template.objects.exclude(category__in=valid_values).update(category='promotional')


def backwards(apps, schema_editor):
    Template = apps.get_model('templates', 'Template')

    reverse_mapping = {
        'promotional': 'general',
        'transactional': 'notification',
        'remainder': 'reminder',
        'welcome': 'welcome',
        'renewal': 'renewal',
        'payment': 'payment',
    }

    for new_value, old_value in reverse_mapping.items():
        Template.objects.filter(category=new_value).update(category=old_value)

    # Values that did not exist previously (e.g., 'claims') default to 'general'
    Template.objects.exclude(category__in=reverse_mapping.values()).update(category='general')


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_template_dlt_template_id_template_tags_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
