# Generated by Django 4.2.7 on 2025-10-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_migrate_template_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_dlt_approved',
            field=models.BooleanField(default=False, help_text='Whether the template is approved on the DLT platform'),
        ),
    ]
