# Generated by Django 5.2.7 on 2025-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_template_is_dlt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this template has been used'),
        ),
    ]
