# Generated by Django 5.2.7 on 2025-12-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_template_usage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('promotional', 'Promotional'), ('transactional', 'Transactional'), ('renewal', 'Renewal'), ('welcome', 'Welcome'), ('payment', 'Payment'), ('claims', 'Claims'), ('remainder', 'Remainder'), ('general', 'General'), ('inquiry', 'Inquiry'), ('complaint', 'Complaint')], default='promotional', max_length=20),
        ),
    ]
