# Generated by Django 4.2.17 on 2025-12-19 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, verbose_name='Unit Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_cases', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('manager', models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hierarchy_branch',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, verbose_name='Unit Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_cases', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hierarchy.branch')),
                ('manager', models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hierarchy_department',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, verbose_name='Unit Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_cases', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('manager', models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hierarchy_region',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, verbose_name='Unit Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_cases', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hierarchy.department')),
                ('manager', models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hierarchy_team',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, verbose_name='Unit Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_cases', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('manager', models.ForeignKey(db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_managed', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hierarchy.region')),
            ],
            options={
                'db_table': 'hierarchy_state',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='hierarchy.state'),
        ),
    ]
