# Generated by Django 4.2.7 on 2025-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='current_work_step',
            field=models.CharField(blank=True, choices=[('initial_contact', 'Initial Contact'), ('document_collection', 'Document Collection'), ('verification', 'Verification'), ('premium_calculation', 'Premium Calculation'), ('payment_processing', 'Payment Processing'), ('policy_generation', 'Policy Generation'), ('final_review', 'Final Review'), ('delivery', 'Delivery')], help_text='Current work step in the renewal process', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('document_pending', 'Document Pending'), ('customer_contact_required', 'Customer Contact Required'), ('payment_processing', 'Payment Processing'), ('verification_in_progress', 'Verification In Progress'), ('approval_required', 'Approval Required'), ('ready_for_renewal', 'Ready For Renewal'), ('follow_up_required', 'Follow-up Required'), ('under_review', 'Under Review')], help_text='Current sub-status of the case', max_length=50, null=True),
        ),
    ]
