# Generated by Django 4.2.17 on 2026-01-22 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_document_language_and_more'),
        ('renewals', '0036_merge_20260122_1243'),
        ('clients', '0003_alter_client_code_alter_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNCSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_checking', models.BooleanField(default=True)),
                ('block_contacts', models.BooleanField(default=True)),
                ('auto_check', models.BooleanField(default=True)),
                ('allow_overrides', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DNCRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('dnc_type', models.CharField(choices=[('Phone Only', 'Phone Only'), ('Email Only', 'Email Only'), ('Both Phone & Email', 'Both Phone & Email')], max_length=50)),
                ('source', models.CharField(choices=[('Customer Request', 'Customer Request'), ('Government Registry', 'Government Registry'), ('Manual Entry', 'Manual Entry'), ('System Generated', 'System Generated')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('allow_override_requests', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_entries', to='clients.client')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_entries', to='customers.customer')),
                ('renewal_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_records', to='renewals.renewalcase')),
            ],
        ),
        migrations.CreateModel(
            name='DNCOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(max_length=50)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('authorized_by', models.CharField(default='System User', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dnc_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='dnc.dncregistry')),
            ],
        ),
    ]
