# Generated by Django 4.2.7 on 2025-11-03 11:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_channels', '0010_remove_customer_from_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Distribution channel name', max_length=255)),
                ('channel_type', models.CharField(choices=[('Agent Network', 'Agent Network'), ('Insurance Broker', 'Insurance Broker'), ('Bank Partnership', 'Bank Partnership'), ('Corporate Partner', 'Corporate Partner'), ('Online Platform', 'Online Platform'), ('Direct Sales', 'Direct Sales')], help_text='Type of distribution channel', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the distribution channel', null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('region', models.CharField(blank=True, help_text='Geographical region covered', max_length=100, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate as a percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('target_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Target revenue in currency', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', help_text='Current status of the distribution channel', max_length=20)),
                ('partner_since', models.DateField(blank=True, help_text='Date when partnership started', null=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Related communication channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_channels', to='business_channels.channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distribution_channel',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['channel_type'], name='distributio_channel_c233c9_idx'), models.Index(fields=['status'], name='distributio_status_b1dc69_idx'), models.Index(fields=['region'], name='distributio_region_b0eb15_idx'), models.Index(fields=['channel'], name='distributio_channel_a2ce44_idx'), models.Index(fields=['partner_since'], name='distributio_partner_1e15ff_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='distributionchannel',
            constraint=models.CheckConstraint(check=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='valid_commission_rate'),
        ),
        migrations.AddConstraint(
            model_name='distributionchannel',
            constraint=models.CheckConstraint(check=models.Q(('target_revenue__gte', 0)), name='positive_target_revenue'),
        ),
    ]
