# Generated by Django 4.2.7 on 2025-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
