# Generated by Django 5.2.6 on 2025-10-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_auto_20251016_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Available to all users'),
        ),
    ]
