# Generated by Django 4.2.7 on 2025-10-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0005_alter_emailtemplate_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplatecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplatecategory',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplatecategory',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='emailtemplate',
            name='email_templ_categor_1f004b_idx',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='category',
        ),
        migrations.DeleteModel(
            name='EmailTemplateCategory',
        ),
    ]
