# Generated by Django 4.2.7 on 2025-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('batch_code', models.CharField(help_text='Batch code for tracking Excel import batches (e.g., BATCH-2025-07-25-A)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('due', 'Due'), ('overdue', 'Overdue'), ('not_required', 'Not Required'), ('assigned', 'Assigned'), ('failed', 'Failed'), ('uploaded', 'Uploaded')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('renewal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('communication_attempts', models.IntegerField(default=0)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'renewal_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
