# Generated by Django 4.2.7 on 2025-07-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_channels', '0001_initial'),
        ('renewals', '0001_initial'),
        ('policies', '0002_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_renewal_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Channel through which this renewal case was initiated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_cases', to='business_channels.channel'),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_cases', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_cases', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['status'], name='renewal_cas_status_5be8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['priority'], name='renewal_cas_priorit_182f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['assigned_to'], name='renewal_cas_assigne_6cb989_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['channel'], name='renewal_cas_channel_f4e671_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['batch_code'], name='renewal_cas_batch_c_5c9465_idx'),
        ),
    ]
