# Generated by Django 4.2.7 on 2025-07-31 13:24

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0003_update_channel_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='renewalcase',
            name='renewal_cas_channel_f4e671_idx',
        ),
        migrations.AlterField(
            model_name='renewalcase',
            name='channel',
            field=models.ForeignKey(blank=True, db_column='channel_id', help_text='Channel through which this renewal case was initiated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_cases', to='business_channels.channel'),
        ),
        migrations.RenameField(
            model_name='renewalcase',
            old_name='channel',
            new_name='channel_id',
        ),
        migrations.AddIndex(
            model_name='renewalcase',
            index=models.Index(fields=['channel_id'], name='renewal_cas_channel_f4e671_idx'),
        ),
    ]
