# Generated by Django 4.2.7 on 2025-08-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renewals', '0004_remove_renewalcase_renewal_cas_channel_f4e671_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sub_status', models.CharField(choices=[('document_pending', 'Document Pending'), ('customer_contact_required', 'Customer Contact Required'), ('payment_processing', 'Payment Processing'), ('verification_in_progress', 'Verification In Progress'), ('approval_required', 'Approval Required'), ('ready_for_renewal', 'Ready For Renewal'), ('follow_up_required', 'Follow-up Required'), ('under_review', 'Under Review')], help_text='Current sub-status of the case', max_length=50)),
                ('current_work_step', models.CharField(choices=[('initial_contact', 'Initial Contact'), ('document_collection', 'Document Collection'), ('verification', 'Verification'), ('premium_calculation', 'Premium Calculation'), ('payment_processing', 'Payment Processing'), ('policy_generation', 'Policy Generation'), ('final_review', 'Final Review'), ('delivery', 'Delivery')], help_text='Current work step in the renewal process', max_length=50)),
                ('next_follow_up_date', models.DateTimeField(blank=True, help_text='Date and time for next follow-up', null=True)),
                ('next_action_plan', models.TextField(blank=True, help_text='Description of the next planned action')),
                ('comment', models.TextField(blank=True, help_text='Additional comments or notes for this log entry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('renewal_case', models.ForeignKey(help_text='Related renewal case', on_delete=django.db.models.deletion.CASCADE, related_name='case_logs', to='renewals.renewalcase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Log',
                'verbose_name_plural': 'Case Logs',
                'db_table': 'case_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['renewal_case', 'created_at'], name='case_logs_renewal_c28bde_idx'), models.Index(fields=['sub_status'], name='case_logs_sub_sta_48ffaa_idx'), models.Index(fields=['current_work_step'], name='case_logs_current_496fbf_idx'), models.Index(fields=['next_follow_up_date'], name='case_logs_next_fo_bd4d7b_idx'), models.Index(fields=['created_at'], name='case_logs_created_131692_idx')],
            },
        ),
    ]
