# Generated by Django 4.2.7 on 2025-08-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0005_caselog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseLog',
        ),
    ]
