# Generated by Django 4.2.7 on 2025-08-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0006_add_renewed_status'),
        ('renewals', '0006_delete_caselog'),
    ]

    operations = [
    ]
