# Generated by Django 4.2.7 on 2025-08-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payments', '0002_remove_customerpayment_customer_pa_renewal_c4446f_idx_and_more'),
        ('renewals', '0008_fix_renewed_status_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalcase',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='renewalcase',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='customer_payment',
            field=models.ForeignKey(blank=True, db_column='customer_payment_id', help_text='Payment record associated with this renewal case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_cases', to='customer_payments.customerpayment'),
        ),
    ]
