# Generated by Django 4.2.7 on 2025-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0009_remove_renewalcase_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Payment status - auto-generated from customer_payments table', max_length=20),
        ),
    ]
