# Generated by Django 4.2.7 on 2025-09-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0010_add_payment_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalcase',
            name='communication_attempts',
        ),
        migrations.RemoveField(
            model_name='renewalcase',
            name='last_contact_date',
        ),
    ]
