# Generated by Django 4.2.7 on 2025-09-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0011_remove_communication_attempts_and_last_contact_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='renewalcase',
            name='renewal_cas_priorit_182f8d_idx',
        ),
        migrations.RemoveField(
            model_name='renewalcase',
            name='priority',
        ),
    ]
