# Generated by Django 4.2.7 on 2025-11-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0013_update_status_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Date for the next follow-up', null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='follow_up_time',
            field=models.TimeField(blank=True, help_text='Time for the next follow-up', null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes for the case'),
        ),
    ]
