# Generated by Django 5.2.6 on 2025-11-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_channels', '0010_remove_customer_from_channel'),
        ('renewals', '0014_add_follow_up_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Channel associated with this renewal case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_cases', to='business_channels.channel'),
        ),
    ]
