# Generated by Django 5.2.6 on 2025-11-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0015_renewalcase_channel'),
        ('teams', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_cases', to='teams.team'),
        ),
    ]
