# Generated by Django 5.2.6 on 2025-11-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0016_renewalcase_assigned_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalcase',
            name='channel',
        ),
    ]
