# Generated by Django 5.2.7 on 2025-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0016_renewalcase_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='competitor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='lost_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('competitor_offer', 'Competitor Offer'), ('price_too_high', 'Price Too High'), ('better_coverage', 'Better Coverage Elsewhere'), ('financial_constraints', 'Financial Constraints'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='renewalcase',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('failed', 'Failed'), ('renewed', 'Renewed'), ('not_interested', 'Not Interested'), ('lost', 'Lost'), ('dnc_email', 'DNC email'), ('dnc_whatsapp', 'DNC WhatsApp'), ('dnc_sms', 'DNC SMS'), ('dnc_call', 'DNC Call'), ('dnc_bot_calling', 'DNC Bot Calling'), ('payment_failed', 'Payment Failed'), ('customer_postponed', 'Customer Postponed')], default='pending', max_length=30),
        ),
    ]
