# Generated by Django 5.2.7 on 2025-11-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0018_remove_renewalcase_competitor_name_competitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='not_interested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='not_interested_reason',
            field=models.CharField(blank=True, choices=[('already_have_coverage', 'Already Have Coverage'), ('cannot_afford', 'Cannot Afford Premium'), ('moving_city', 'Moving to Another City'), ('policy_terms', 'Policy Terms Not Suitable'), ('no_immediate_need', 'No Immediate Need'), ('happy_with_current', 'Happy with Current Plan'), ('recently_purchased', 'Recently Purchased Elsewhere'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
