# Generated by Django 5.2.7 on 2025-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0019_renewalcase_not_interested_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='renewalcase',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='If True, this case only appears in the Archived dashboard'),
        ),
        migrations.AlterField(
            model_name='renewalcase',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('failed', 'Failed'), ('renewed', 'Renewed'), ('not_interested', 'Not Interested'), ('lost', 'Lost'), ('expired', 'Expired'), ('declined', 'Declined'), ('dnc_email', 'DNC email'), ('dnc_whatsapp', 'DNC WhatsApp'), ('dnc_sms', 'DNC SMS'), ('dnc_call', 'DNC Call'), ('dnc_bot_calling', 'DNC Bot Calling'), ('payment_failed', 'Payment Failed'), ('customer_postponed', 'Customer Postponed')], default='pending', max_length=30),
        ),
    ]
