# Generated by Django 5.2.6 on 2025-11-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0018_renewalcase_channel'),
        ('renewals', '0020_renewalcase_archived_date_and_more'),
    ]

    operations = [
    ]
