# Generated by Django 5.2.7 on 2025-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0021_merge_20251120_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalcase',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
