# Generated by Django 5.2.7 on 2025-11-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0018_renewalcase_channel'),
        ('renewals', '0022_renewalcase_priority'),
    ]

    operations = [
    ]
