# Generated by Django 4.2.17 on 2025-11-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0021_merge_20251120_0648'),
        ('renewals', '0021_merge_20251120_1544'),
        ('renewals', '0022_renewalcase_priority'),
    ]

    operations = [
    ]
