# Generated by Django 5.2.6 on 2025-11-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0021_merge_20251120_1544'),
        ('renewals', '0022_renewalcase_priority'),
    ]

    operations = [
    ]
