# Generated by Django 5.2.7 on 2025-11-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0023_merge_20251120_1828'),
        ('renewals', '0023_merge_20251123_1620'),
    ]

    operations = [
    ]
