# Generated by Django 4.2.17 on 2025-11-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0023_merge_20251120_1256'),
        ('renewals', '0023_merge_20251120_1828'),
    ]

    operations = [
    ]
