# Generated by Django 4.2.17 on 2025-11-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0023_merge_20251123_1620'),
        ('renewals', '0024_merge_20251121_0644'),
    ]

    operations = [
    ]
