# Generated by Django 5.2.7 on 2025-11-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0024_merge_20251124_1800'),
        ('renewals', '0024_merge_20251125_0957'),
    ]

    operations = [
    ]
