# Generated by Django 5.2.7 on 2025-11-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0025_merge_20251125_1527'),
        ('renewals', '0025_merge_20251125_1604'),
    ]

    operations = [
    ]
