# Generated by Django 4.2.17 on 2025-11-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0024_merge_20251124_1800'),
        ('renewals', '0025_merge_20251124_0924'),
    ]

    operations = [
    ]
