# Generated by Django 4.2.17 on 2025-11-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0025_merge_20251125_1527'),
        ('renewals', '0025_merge_20251125_1604'),
        ('renewals', '0026_merge_20251124_1236'),
    ]

    operations = [
    ]
