# Generated by Django 4.2.17 on 2025-11-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0026_merge_20251126_1531'),
        ('renewals', '0027_merge_20251126_0721'),
    ]

    operations = [
    ]
