# Generated by Django 5.2.6 on 2025-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0027_alter_competitor_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalcase',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('competitor_offer', 'Competitor Offer'), ('price_too_high', 'Price Too High'), ('better_coverage', 'Better Coverage Elsewhere'), ('financial_constraints', 'Financial Constraints'), ('other', 'Other'), ('changed_insurance_provider', 'Changed Insurance Provider')], max_length=30, null=True),
        ),
    ]
