# Generated by Django 4.2.17 on 2025-11-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0028_alter_renewalcase_lost_reason'),
        ('renewals', '0028_merge_20251128_0448'),
    ]

    operations = [
    ]
