# Generated by Django 5.2.6 on 2025-12-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0026_merge_20251126_1050'),
        ('renewals', '0028_alter_renewalcase_lost_reason'),
    ]

    operations = [
    ]
