# Generated by Django 5.2.7 on 2025-12-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0029_merge_20251128_0718'),
        ('renewals', '0029_merge_20251203_1258'),
        ('renewals', '0029_merge_20251203_1646'),
    ]

    operations = [
    ]
