# Generated by Django 4.2.17 on 2025-12-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0029_merge_20251128_0718'),
        ('renewals', '0029_merge_20251203_1646'),
    ]

    operations = [
    ]
