# Generated by Django 5.2.6 on 2025-12-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0029_merge_20251128_0718'),
        ('renewals', '0029_merge_20251203_1646'),
    ]

    operations = [
    ]
