# Generated by Django 5.2.7 on 2025-12-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0030_merge_20251203_1749'),
        ('renewals', '0030_merge_20251209_1053'),
    ]

    operations = [
    ]
