# Generated by Django 5.2.6 on 2025-12-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0030_merge_20251203_1749'),
        ('renewals', '0030_merge_20251209_1053'),
    ]

    operations = [
    ]
