# Generated by Django 5.2.6 on 2025-12-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0031_merge_20251210_1324'),
        ('renewals', '0031_merge_20251210_1341'),
    ]

    operations = [
    ]
