# Generated by Django 4.2.17 on 2025-12-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0030_merge_20251203_2046'),
        ('renewals', '0031_merge_20251210_1324'),
        ('renewals', '0031_merge_20251210_1341'),
    ]

    operations = [
    ]
