# Generated by Django 5.2.7 on 2025-12-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0030_merge_20251203_2046'),
        ('renewals', '0032_merge_20251218_1110'),
    ]

    operations = [
    ]
