# Generated by Django 5.2.6 on 2025-12-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0032_merge_20251217_1201'),
        ('renewals', '0033_merge_20251219_1311'),
    ]

    operations = [
    ]
