# Generated by Django 5.2.7 on 2025-12-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0032_merge_20251219_1110'),
        ('renewals', '0034_merge_20251223_1213'),
    ]

    operations = [
    ]
