# Generated by Django 4.2.17 on 2026-01-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0035_merge_20251226_1617'),
        ('renewals', '0035_merge_20251229_1039'),
    ]

    operations = [
    ]
