# Generated by Django 4.2.17 on 2026-01-28 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=False, help_text='Enable AI-powered assistance')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google_ai', 'Google AI'), ('ollama', 'Ollama (Local)')], default='openai', help_text='Select the AI service provider', max_length=50)),
                ('ai_model', models.CharField(blank=True, help_text='Select the AI model to use', max_length=100, null=True)),
                ('api_key', models.TextField(blank=True, help_text='Enter your AI provider API key', null=True)),
                ('azure_endpoint', models.URLField(blank=True, help_text='Azure OpenAI endpoint URL', null=True)),
                ('azure_deployment_name', models.CharField(blank=True, help_text='Azure deployment name', max_length=100, null=True)),
                ('azure_api_version', models.CharField(default='2024-02-01', help_text='Azure API version', max_length=20)),
                ('google_project_id', models.CharField(blank=True, help_text='Google Cloud Project ID', max_length=100, null=True)),
                ('temperature', models.FloatField(default=0.7, help_text='Controls response creativity (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum response length')),
                ('response_timeout', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('fallback_enabled', models.BooleanField(default=True, help_text='Show fallback message when AI is unavailable')),
                ('renewal_insights', models.BooleanField(default=True)),
                ('process_optimization', models.BooleanField(default=True)),
                ('customer_retention', models.BooleanField(default=True)),
                ('communication_strategies', models.BooleanField(default=True)),
                ('rate_limit_enabled', models.BooleanField(default=True, help_text='Prevent API quota exhaustion')),
                ('requests_per_minute', models.PositiveIntegerField(default=60, help_text='Maximum requests per minute')),
                ('requests_per_hour', models.PositiveIntegerField(default=1000, help_text='Maximum requests per hour')),
                ('knowledge_base_enabled', models.BooleanField(default=True, help_text='Use internal knowledge for better responses')),
                ('kb_auto_update', models.BooleanField(default=True, help_text='Automatically update knowledge base')),
                ('kb_last_updated', models.DateTimeField(blank=True, null=True)),
                ('ollama_base_url', models.URLField(blank=True, default='http://localhost:11434', help_text='Ollama server URL')),
                ('ollama_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ollama_keep_alive', models.CharField(default='5m', max_length=20)),
                ('ollama_stream', models.BooleanField(default=False)),
                ('ollama_system_prompt', models.TextField(blank=True, null=True)),
                ('ollama_options', models.JSONField(blank=True, default=dict)),
                ('ollama_available_models', models.JSONField(blank=True, default=list)),
                ('ollama_last_model_refresh', models.DateTimeField(blank=True, null=True)),
                ('data_retention_period', models.PositiveIntegerField(default=12, help_text='How long to keep archived data (months)')),
                ('auto_backup', models.BooleanField(default=True, help_text='Automatically backup data to cloud storage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
