# Generated by Django 4.2.7 on 2025-08-11 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAdditionalBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('benefit_type', models.CharField(choices=[('key_replacement', 'Key Replacement'), ('return_to_invoice', 'Return to Invoice'), ('personal_accident', 'Personal Accident'), ('passenger_cover', 'Passenger Cover'), ('consumables_cover', 'Consumables Cover'), ('roadside_assistance', 'Roadside Assistance'), ('zero_depreciation', 'Zero Depreciation'), ('engine_protection', 'Engine Protection'), ('ncb_protection', 'NCB Protection'), ('emergency_support', 'Emergency Support'), ('medical_expenses', 'Medical Expenses'), ('legal_liability', 'Legal Liability'), ('towing_charges', 'Towing Charges'), ('daily_allowance', 'Daily Allowance'), ('general', 'General')], db_index=True, default='general', help_text='Type of additional benefit', max_length=50)),
                ('benefit_name', models.CharField(help_text='Name of the additional benefit', max_length=200)),
                ('benefit_description', models.TextField(help_text='Detailed description of the benefit')),
                ('benefit_value', models.CharField(blank=True, help_text='Value or amount associated with the benefit (if applicable)', max_length=500)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Coverage amount for this benefit', max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this benefit is currently active')),
                ('is_optional', models.BooleanField(default=True, help_text='Whether this benefit is optional or mandatory')),
                ('premium_impact', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional premium for this benefit', max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this benefit')),
                ('terms_conditions', models.TextField(blank=True, help_text='Specific terms and conditions for this benefit')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional information about the benefit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Policy this benefit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policy_additional_benefits', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_additional_benefits',
                'ordering': ['display_order', 'benefit_name'],
                'indexes': [models.Index(fields=['policy', 'is_active'], name='policy_addi_policy__8c29e7_idx'), models.Index(fields=['benefit_type', 'is_active'], name='policy_addi_benefit_04a1b6_idx'), models.Index(fields=['policy', 'benefit_type'], name='policy_addi_policy__aa8969_idx'), models.Index(fields=['display_order'], name='policy_addi_display_c56451_idx')],
                'unique_together': {('policy', 'benefit_name')},
            },
        ),
    ]
