# Generated by Django 4.2.7 on 2025-08-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_coverages', '0003_remove_policycoverage_policy_cove_policy__7c35eb_idx_and_more'),
        ('policy_additional_benefits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policyadditionalbenefit',
            name='policy_addi_policy__8c29e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='policyadditionalbenefit',
            name='policy_addi_policy__aa8969_idx',
        ),
        migrations.AlterUniqueTogether(
            name='policyadditionalbenefit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='policyadditionalbenefit',
            name='benefit_category',
            field=models.CharField(blank=True, help_text='Category of the benefit', max_length=100),
        ),
        migrations.AddField(
            model_name='policyadditionalbenefit',
            name='policy_coverages',
            field=models.ForeignKey(default=1, help_text='Policy coverage this benefit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='additional_benefits', to='policy_coverages.policycoverage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyadditionalbenefit',
            name='benefit_type',
            field=models.CharField(choices=[('key_replacement', 'Key Replacement'), ('return_to_invoice', 'Return to Invoice'), ('personal_accident', 'Personal Accident'), ('passenger_cover', 'Passenger Cover'), ('consumables_cover', 'Consumables Cover'), ('roadside_assistance', 'Roadside Assistance'), ('zero_depreciation', 'Zero Depreciation'), ('engine_protection', 'Engine Protection'), ('ncb_protection', 'NCB Protection'), ('emergency_support', 'Emergency Support'), ('medical_expenses', 'Medical Expenses'), ('legal_liability', 'Legal Liability'), ('towing_charges', 'Towing Charges'), ('daily_allowance', 'Daily Allowance'), ('general', 'General')], db_index=True, default='general', help_text='Type of additional benefit (legacy field)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='policyadditionalbenefit',
            unique_together={('policy_coverages', 'benefit_name')},
        ),
        migrations.AddIndex(
            model_name='policyadditionalbenefit',
            index=models.Index(fields=['policy_coverages', 'is_active'], name='policy_addi_policy__68f255_idx'),
        ),
        migrations.AddIndex(
            model_name='policyadditionalbenefit',
            index=models.Index(fields=['policy_coverages', 'benefit_type'], name='policy_addi_policy__af832d_idx'),
        ),
        migrations.AddIndex(
            model_name='policyadditionalbenefit',
            index=models.Index(fields=['benefit_category'], name='policy_addi_benefit_10bf12_idx'),
        ),
        migrations.AddIndex(
            model_name='policyadditionalbenefit',
            index=models.Index(fields=['policy_coverages', 'benefit_category'], name='policy_addi_policy__211806_idx'),
        ),
        migrations.RemoveField(
            model_name='policyadditionalbenefit',
            name='policy',
        ),
    ]
