# Generated by Django 4.2.7 on 2025-08-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerpayment',
            name='customer_pa_renewal_c4446f_idx',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='renewal_case',
        ),
    ]
