# Generated by Django 4.2.7 on 2025-09-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0009_remove_renewalcase_payment_date_and_more'),
        ('customers', '0003_remove_customer_communication_preferences'),
        ('customer_payments', '0002_remove_customerpayment_customer_pa_renewal_c4446f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='renewal_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='renewals.renewalcase'),
        ),
    ]
