# Generated by Django 4.2.7 on 2025-10-16 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(help_text='Unique session identifier for this conversation', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Conversation title (auto-generated from first message)', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', help_text='Current status of the conversation', max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data for the conversation')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When this conversation was started')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Total number of messages in this conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who initiated this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='upload_chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_chatbot_conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UploadChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], db_index=True, help_text='Role of the message sender', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (tokens used, model, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this message was sent')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether this message has been edited')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='upload_chatbot.uploadchatbotconversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_chatbot_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='upload_chat_convers_6065ad_idx'), models.Index(fields=['role', 'timestamp'], name='upload_chat_role_baa985_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadchatbotconversation',
            index=models.Index(fields=['user', 'status'], name='upload_chat_user_id_d530ef_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadchatbotconversation',
            index=models.Index(fields=['session_id'], name='upload_chat_session_61e6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadchatbotconversation',
            index=models.Index(fields=['last_activity'], name='upload_chat_last_ac_8e5a28_idx'),
        ),
    ]
