# Generated by Django 4.2.7 on 2025-09-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_customer_communication_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_premiums_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total premiums paid by customer', max_digits=15)),
                ('on_time_payment_rate', models.FloatField(default=0.0, help_text='Percentage of on-time payments')),
                ('total_payments_made', models.PositiveIntegerField(default=0, help_text='Total number of payments made')),
                ('most_used_mode', models.CharField(blank=True, help_text='Most frequently used payment method', max_length=50)),
                ('average_payment_timing', models.CharField(blank=True, help_text="Average payment timing (e.g., '5 days early')", max_length=100)),
                ('payment_reliability', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='average', help_text='Overall payment reliability rating', max_length=20)),
                ('preferred_payment_method', models.CharField(blank=True, help_text="Customer's preferred payment method", max_length=50)),
                ('average_payment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Average payment amount', max_digits=12)),
                ('customer_since_years', models.PositiveIntegerField(default=0, help_text='Number of years as customer')),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date of last payment', null=True)),
                ('payment_frequency', models.CharField(blank=True, help_text='Payment frequency pattern', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer these payment insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_insights', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='payment_ins_custome_b101f5_idx'), models.Index(fields=['payment_reliability'], name='payment_ins_payment_3bbb5e_idx'), models.Index(fields=['on_time_payment_rate'], name='payment_ins_on_time_a1fc89_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfileInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('active_policies', models.PositiveIntegerField(default=0, help_text='Number of active policies')),
                ('family_policies', models.PositiveIntegerField(default=0, help_text='Number of family policies')),
                ('expired_lapsed_policies', models.PositiveIntegerField(default=0, help_text='Number of expired/lapsed policies')),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, help_text='Customer lifetime value', max_digits=15)),
                ('total_paid_ytd', models.DecimalField(decimal_places=2, default=0, help_text='Total paid year-to-date', max_digits=15)),
                ('customer_segment', models.CharField(blank=True, help_text='Customer segment classification', max_length=50)),
                ('engagement_level', models.CharField(blank=True, help_text='Customer engagement level', max_length=50)),
                ('policy_portfolio', models.JSONField(default=dict, help_text="Customer's policy portfolio breakdown")),
                ('overall_risk_score', models.FloatField(default=0.0, help_text='Overall risk score (0-100)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer these profile insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='profile_insights', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profile_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_pr_custome_32b1ac_idx'), models.Index(fields=['customer_segment'], name='customer_pr_custome_906be7_idx'), models.Index(fields=['engagement_level'], name='customer_pr_engagem_dcf611_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('insight_type', models.CharField(choices=[('payment', 'Payment Insights'), ('communication', 'Communication Insights'), ('claims', 'Claims Insights'), ('profile', 'Customer Profile'), ('behavior', 'Behavior Analysis')], db_index=True, help_text='Type of insight', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When these insights were last calculated')),
                ('data', models.JSONField(default=dict, help_text='Structured insight data')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this insight is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer these insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_insights', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_insights',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['customer', 'insight_type'], name='customer_in_custome_f4f569_idx'), models.Index(fields=['calculated_at'], name='customer_in_calcula_f8b9f3_idx'), models.Index(fields=['is_active'], name='customer_in_is_acti_6e0d46_idx')],
                'unique_together': {('customer', 'insight_type')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_communications', models.PositiveIntegerField(default=0, help_text='Total number of communications')),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average response time in hours')),
                ('satisfaction_rating', models.FloatField(default=0.0, help_text='Average satisfaction rating (1-5)')),
                ('last_contact_date', models.DateTimeField(blank=True, help_text='Date of last contact', null=True)),
                ('channel_breakdown', models.JSONField(default=dict, help_text='Communication breakdown by channel')),
                ('preferred_channel', models.CharField(blank=True, help_text="Customer's preferred communication channel", max_length=50)),
                ('communication_frequency', models.CharField(blank=True, help_text='Communication frequency pattern', max_length=50)),
                ('response_rate', models.FloatField(default=0.0, help_text='Customer response rate percentage')),
                ('escalation_count', models.PositiveIntegerField(default=0, help_text='Number of escalated communications')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer these communication insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='communication_insights', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communication_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='communicati_custome_cc0261_idx'), models.Index(fields=['satisfaction_rating'], name='communicati_satisfa_eb027a_idx'), models.Index(fields=['last_contact_date'], name='communicati_last_co_7c38e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaimsInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_claims', models.PositiveIntegerField(default=0, help_text='Total number of claims')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total approved claim amount', max_digits=15)),
                ('avg_processing_time', models.PositiveIntegerField(default=0, help_text='Average processing time in days')),
                ('approval_rate', models.FloatField(default=0.0, help_text='Claim approval rate percentage')),
                ('claims_by_type', models.JSONField(default=dict, help_text='Claims breakdown by type')),
                ('claims_by_status', models.JSONField(default=dict, help_text='Claims breakdown by status')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', help_text='Overall claims risk level', max_length=20)),
                ('last_claim_date', models.DateTimeField(blank=True, help_text='Date of last claim', null=True)),
                ('claim_frequency', models.CharField(blank=True, help_text='Claim frequency pattern', max_length=50)),
                ('total_claimed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount claimed', max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer these claims insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='claims_insights', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='claims_insi_custome_53c6a2_idx'), models.Index(fields=['risk_level'], name='claims_insi_risk_le_355a44_idx'), models.Index(fields=['approval_rate'], name='claims_insi_approva_7ce1d6_idx')],
            },
        ),
    ]
