# Generated by Django 5.2.6 on 2025-09-27 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0001_initial'),
        ('customers', '0003_remove_customer_communication_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimsinsight',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='claimsinsight',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='claimsinsight',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='claimsinsight',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='communicationinsight',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='communicationinsight',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='communicationinsight',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='communicationinsight',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customerprofileinsight',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerprofileinsight',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerprofileinsight',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='customerprofileinsight',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentinsight',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentinsight',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentinsight',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='paymentinsight',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='customerinsight',
            name='customer_in_custome_f4f569_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerinsight',
            name='customer_in_is_acti_6e0d46_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customerinsight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='cache_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the cached insights expire', null=True),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='claims_insights',
            field=models.JSONField(default=dict, help_text='Claims-related insights and metrics'),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='communication_insights',
            field=models.JSONField(default=dict, help_text='Communication-related insights and metrics'),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='is_cached',
            field=models.BooleanField(default=False, help_text='Whether insights are cached and up-to-date'),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='payment_insights',
            field=models.JSONField(default=dict, help_text='Payment-related insights and metrics'),
        ),
        migrations.AddField(
            model_name='customerinsight',
            name='profile_insights',
            field=models.JSONField(default=dict, help_text='Customer profile and behavioral insights'),
        ),
        migrations.AlterField(
            model_name='customerinsight',
            name='customer',
            field=models.ForeignKey(help_text='Customer these insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_insights', to='customers.customer', unique=True),
        ),
        migrations.AddIndex(
            model_name='customerinsight',
            index=models.Index(fields=['customer'], name='customer_in_custome_b38311_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinsight',
            index=models.Index(fields=['is_cached'], name='customer_in_is_cach_7d8ed2_idx'),
        ),
        migrations.DeleteModel(
            name='ClaimsInsight',
        ),
        migrations.DeleteModel(
            name='CommunicationInsight',
        ),
        migrations.DeleteModel(
            name='CustomerProfileInsight',
        ),
        migrations.DeleteModel(
            name='PaymentInsight',
        ),
        migrations.RemoveField(
            model_name='customerinsight',
            name='data',
        ),
        migrations.RemoveField(
            model_name='customerinsight',
            name='insight_type',
        ),
        migrations.RemoveField(
            model_name='customerinsight',
            name='is_active',
        ),
    ]
