# Generated by Django 5.2.6 on 2025-09-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0002_remove_claimsinsight_created_by_and_more'),
        ('customers', '0003_remove_customer_communication_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsight',
            name='customer',
            field=models.OneToOneField(help_text='Customer these insights belong to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_insights', to='customers.customer'),
        ),
    ]
