# Generated by Django 4.2.7 on 2025-07-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiratelimit',
            index=models.Index(fields=['identifier', 'window_start'], name='core_apirat_identif_7bab64_idx'),
        ),
        migrations.AddIndex(
            model_name='apiratelimit',
            index=models.Index(fields=['endpoint', 'window_start'], name='core_apirat_endpoin_0d87ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiratelimit',
            unique_together={('identifier', 'endpoint', 'window_start')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', 'created_at'], name='core_auditl_user_id_5afea4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
    ]
