# Generated by Django 5.2.6 on 2025-09-12 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_channels', '0009_channel_customer_channel_channel_custome_2776ba_idx'),
        ('customer_payments', '0003_customerpayment_customer_and_more'),
        ('customers', '0003_remove_customer_communication_preferences'),
        ('policies', '0004_policybeneficiary'),
        ('renewals', '0009_remove_renewalcase_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonRenewalTimelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_pattern', models.CharField(default='Pays 7-14 days before due date', help_text="e.g., 'Pays 7–14 days before due date'", max_length=100)),
                ('reminder_days', models.JSONField(default=list, help_text='Days before due date to send reminders, e.g. [-30, -14, -7]')),
                ('auto_renewal_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Description of these timeline settings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_common_timeline_settings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_common_timeline_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Common Renewal Timeline Settings',
                'verbose_name_plural': 'Common Renewal Timeline Settings',
                'db_table': 'common_renewal_timeline_settings',
            },
        ),
    ]
