# Generated by Django 5.2.6 on 2025-09-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_timeline', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS renewal_timelines CASCADE;",
            reverse_sql="-- Cannot reverse table drop",
        ),
    ]
