# Generated by Django 5.2.6 on 2025-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_timeline', '0002_drop_renewal_timelines_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonrenewaltimelinesettings',
            name='reminder_schedule',
            field=models.JSONField(blank=True, default=list, help_text='Formatted reminder schedule for frontend display'),
        ),
    ]
