# Generated by Django 4.2.7 on 2025-09-17 06:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_payments', '0003_customerpayment_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.IntegerField(help_text='Customer ID reference')),
                ('case_id', models.CharField(help_text='Case ID like CASE-001', max_length=50)),
                ('period', models.CharField(help_text="Installment period e.g. 'March 2024'", max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Installment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(help_text='Installment due date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending', help_text='Installment status', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, help_text='Associated payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='customer_payments.customerpayment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_installments',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='customer_in_custome_831393_idx'), models.Index(fields=['case_id'], name='customer_in_case_id_5e14d2_idx'), models.Index(fields=['status'], name='customer_in_status_b7979b_idx'), models.Index(fields=['due_date'], name='customer_in_due_dat_fd6ee7_idx'), models.Index(fields=['period'], name='customer_in_period_377fa8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customerinstallment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_installment_amount'),
        ),
    ]
