# Generated by Django 5.2.6 on 2025-09-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_installment', '0001_initial'),
        ('customer_payments', '0003_customerpayment_customer_and_more'),
        ('customers', '0003_remove_customer_communication_preferences'),
        ('renewals', '0009_remove_renewalcase_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerinstallment',
            name='customer_in_custome_831393_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerinstallment',
            name='customer_in_case_id_5e14d2_idx',
        ),
        migrations.RemoveField(
            model_name='customerinstallment',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='customerinstallment',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customerinstallment',
            name='customer',
            field=models.ForeignKey(default=1, help_text='Customer reference', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinstallment',
            name='renewal_case',
            field=models.ForeignKey(default=1, help_text='Renewal case reference', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='renewals.renewalcase'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='customerinstallment',
            index=models.Index(fields=['customer'], name='customer_in_custome_831393_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinstallment',
            index=models.Index(fields=['renewal_case'], name='customer_in_renewal_543531_idx'),
        ),
    ]
