# Generated by Django 4.2.7 on 2025-08-07 05:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFamilyMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condition_category', models.CharField(choices=[('cardiovascular', 'Cardiovascular Disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('respiratory', 'Respiratory Disease'), ('neurological', 'Neurological Disorder'), ('genetic', 'Genetic Disorder'), ('mental_health', 'Mental Health'), ('autoimmune', 'Autoimmune Disease'), ('kidney', 'Kidney Disease'), ('liver', 'Liver Disease'), ('blood', 'Blood Disorder'), ('bone', 'Bone/Joint Disease'), ('eye', 'Eye Disease'), ('ear', 'Ear Disease'), ('skin', 'Skin Disease'), ('other', 'Other')], help_text='Category of medical condition', max_length=100)),
                ('condition_name', models.CharField(help_text='Specific name of the medical condition', max_length=100)),
                ('condition_status', models.CharField(choices=[('active', 'Active'), ('controlled', 'Controlled'), ('remission', 'In Remission'), ('cured', 'Cured'), ('chronic', 'Chronic'), ('acute', 'Acute'), ('terminal', 'Terminal'), ('unknown', 'Unknown')], help_text='Current status of the condition', max_length=100)),
                ('family_relation', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandfather_paternal', 'Grandfather (Paternal)'), ('grandmother_paternal', 'Grandmother (Paternal)'), ('grandfather_maternal', 'Grandfather (Maternal)'), ('grandmother_maternal', 'Grandmother (Maternal)'), ('uncle_paternal', 'Uncle (Paternal)'), ('aunt_paternal', 'Aunt (Paternal)'), ('uncle_maternal', 'Uncle (Maternal)'), ('aunt_maternal', 'Aunt (Maternal)'), ('cousin', 'Cousin'), ('other', 'Other')], help_text='Relationship to the customer', max_length=50)),
                ('age_diagnosed', models.IntegerField(blank=True, help_text='Age when condition was diagnosed', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('severity_level', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', help_text='Severity level of the condition', max_length=100)),
                ('current_medication', models.TextField(blank=True, help_text='Current medications for this condition')),
                ('last_checkup_date', models.DateField(blank=True, help_text='Date of last medical checkup for this condition', null=True)),
                ('doctor_name', models.CharField(blank=True, help_text='Name of treating doctor', max_length=100)),
                ('hospital_name', models.CharField(blank=True, help_text='Name of hospital or clinic', max_length=150)),
                ('insurance_impact', models.CharField(choices=[('none', 'No Impact'), ('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('exclusion', 'Exclusion Required'), ('decline', 'Decline Coverage')], default='none', help_text='Impact on insurance coverage', max_length=50)),
                ('premium_loading', models.DecimalField(blank=True, decimal_places=2, help_text='Premium loading percentage due to this condition', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the condition')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this medical condition is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this medical history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='family_medical_history', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_family_medical_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_fa_custome_26c74e_idx'), models.Index(fields=['condition_category'], name='customer_fa_conditi_95c933_idx'), models.Index(fields=['condition_status'], name='customer_fa_conditi_7fc42f_idx'), models.Index(fields=['family_relation'], name='customer_fa_family__7aaed7_idx'), models.Index(fields=['severity_level'], name='customer_fa_severit_8d6997_idx'), models.Index(fields=['insurance_impact'], name='customer_fa_insuran_882149_idx'), models.Index(fields=['is_active'], name='customer_fa_is_acti_3256ab_idx'), models.Index(fields=['last_checkup_date'], name='customer_fa_last_ch_093981_idx')],
            },
        ),
    ]
