# Generated by Django 4.2.7 on 2025-09-22 05:23

from django.db import migrations


def drop_communication_providers_table(apps, schema_editor):
    """Drop the communication_providers table"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS communication_providers CASCADE;")


def reverse_drop_communication_providers_table(apps, schema_editor):
    """Reverse migration - this is not easily reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0005_remove_communication_provider_mapping'),
    ]

    operations = [
        migrations.RunPython(
            drop_communication_providers_table,
            reverse_drop_communication_providers_table
        ),
    ]
