# Generated by Django 4.2.17 on 2025-12-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIntegrationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.CharField(default='daily', max_length=20)),
                ('connected_platforms', models.IntegerField(default=0)),
                ('verified_customers', models.IntegerField(default=0)),
                ('social_connections', models.IntegerField(default=0)),
                ('verification_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('wechat', 'WeChat'), ('line', 'LINE'), ('telegram', 'Telegram')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('facebook_api_key', models.TextField(blank=True, null=True)),
                ('facebook_api_secret', models.TextField(blank=True, null=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_access_token', models.TextField(blank=True, null=True)),
                ('twitter_api_key', models.TextField(blank=True, null=True)),
                ('twitter_api_secret', models.TextField(blank=True, null=True)),
                ('twitter_access_token', models.TextField(blank=True, null=True)),
                ('twitter_access_token_secret', models.TextField(blank=True, null=True)),
                ('instagram_business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_access_token', models.TextField(blank=True, null=True)),
                ('instagram_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_app_secret', models.TextField(blank=True, null=True)),
                ('linkedin_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_access_token', models.TextField(blank=True, null=True)),
                ('linkedin_company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wechat_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wechat_app_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('wechat_merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wechat_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('line_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('line_channel_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('line_channel_access_token', models.TextField(blank=True, null=True)),
                ('telegram_bot_token', models.TextField(blank=True, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_webhook_url', models.CharField(blank=True, max_length=300, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_not_connected', models.BooleanField(default=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialVerificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_social_verification', models.BooleanField(default=True)),
                ('auto_connect_on_verification', models.BooleanField(default=False)),
                ('save_customer_data', models.BooleanField(default=True)),
                ('retention_period', models.CharField(choices=[('90_days', '90 Days'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years')], default='1_year', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=200, null=True)),
                ('is_found', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_url', models.CharField(blank=True, max_length=300, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='social_integration.socialplatform')),
            ],
        ),
    ]
