# Generated by Django 4.2.17 on 2025-12-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialverificationresult',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='socialverificationresult',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='socialverificationresult',
            name='policy_number',
        ),
    ]
