# Generated by Django 4.2.17 on 2026-01-28 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Module',
                'verbose_name_plural': 'Document Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('scraping_type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=20)),
                ('scraping_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('scraping_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Tracks background scraping state', max_length=20)),
                ('scraping_failure_reason', models.TextField(blank=True, help_text='Reason for scraping failure (system generated)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='knowledge_p_status_bc675d_idx'), models.Index(fields=['is_deleted'], name='knowledge_p_is_dele_62f982_idx'), models.Index(fields=['scraping_status'], name='knowledge_p_scrapin_73927b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='knowledge/documents/')),
                ('modules', models.JSONField(default=list)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, help_text='Auto-detected file type (pdf, png, jpg, etc.)', max_length=50, null=True)),
                ('document_size', models.BigIntegerField(blank=True, help_text='Auto-detected file size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ocr_accuracy', models.FloatField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_failure_reason', models.TextField(blank=True, help_text='Exact reason why OCR failed (system generated)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_approved_documents', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_rejected_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status'], name='knowledge_p_status_10d528_idx'), models.Index(fields=['ocr_status'], name='knowledge_p_ocr_sta_12901c_idx'), models.Index(fields=['is_deleted'], name='knowledge_p_is_dele_49744f_idx'), models.Index(fields=['document_type'], name='knowledge_p_documen_c643cb_idx')],
            },
        ),
    ]
