# Generated by Django 4.2.7 on 2025-09-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
