# Generated by Django 5.2.7 on 2025-11-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_role_is_active_alter_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='user_role',
        ),
    ]
