# Generated by Django 5.2.7 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Factory default permissions for reset'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted'),
        ),
    ]
