# Generated by Django 5.2.7 on 2025-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('claims_processing', 'Claims Processing'), ('underwriting', 'Underwriting'), ('customer_service', 'Customer Service'), ('sales_marketing', 'Sales & Marketing'), ('it', 'Information Technology'), ('finance_accounting', 'Finance & Accounting'), ('legal_compliance', 'Legal & Compliance'), ('management', 'Management'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
