# Generated by Django 4.2.17 on 2025-12-04 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallProviderConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this provider, e.g. Twilio Voice', max_length=100)),
                ('provider_type', models.CharField(choices=[('twilio', 'Twilio'), ('exotel', 'Exotel'), ('ubona', 'Ubona')], max_length=20)),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Twilio Account SID (encrypted)', max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Twilio Auth Token (encrypted)', max_length=255, null=True)),
                ('twilio_from_number', models.CharField(blank=True, help_text='Twilio caller number in E.164 format', max_length=20, null=True)),
                ('twilio_status_callback_url', models.URLField(blank=True, help_text='Twilio status callback URL', null=True)),
                ('twilio_voice_url', models.URLField(blank=True, help_text='Twilio Voice URL for outbound calls', null=True)),
                ('exotel_api_key', models.CharField(blank=True, help_text='Exotel API Key (encrypted)', max_length=255, null=True)),
                ('exotel_api_token', models.CharField(blank=True, help_text='Exotel API Token (encrypted)', max_length=255, null=True)),
                ('exotel_account_sid', models.CharField(blank=True, help_text='Exotel Account SID', max_length=255, null=True)),
                ('exotel_subdomain', models.CharField(blank=True, help_text='Exotel subdomain', max_length=100, null=True)),
                ('exotel_caller_id', models.CharField(blank=True, help_text='Exotel Caller ID', max_length=20, null=True)),
                ('ubona_api_key', models.CharField(blank=True, help_text='Ubona API Key (encrypted)', max_length=255, null=True)),
                ('ubona_api_url', models.URLField(blank=True, help_text='Ubona API base URL', null=True)),
                ('ubona_account_sid', models.CharField(blank=True, help_text='Ubona Account SID / project id', max_length=255, null=True)),
                ('ubona_caller_id', models.CharField(blank=True, help_text='Ubona Caller ID', max_length=20, null=True)),
                ('daily_limit', models.PositiveIntegerField(default=1000, help_text='Daily call limit')),
                ('monthly_limit', models.PositiveIntegerField(default=30000, help_text='Monthly call limit')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=10, help_text='Rate limit per minute')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')], default=1, help_text='Priority order when selecting provider')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', help_text='Connection status (connected / disconnected / error / unknown)', max_length=20)),
                ('calls_made_today', models.PositiveIntegerField(default=0)),
                ('calls_made_this_month', models.PositiveIntegerField(default=0)),
                ('last_reset_daily', models.DateField(default=django.utils.timezone.now)),
                ('last_reset_monthly', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_call_providers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_call_providers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_call_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Provider Configuration',
                'verbose_name_plural': 'Call Provider Configurations',
                'db_table': 'call_provider_configs',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallProviderUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calls_made', models.PositiveIntegerField()),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('total_response_time', models.FloatField(default=0.0, help_text='Total API response time in seconds')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='call_provider.callproviderconfig')),
            ],
            options={
                'verbose_name': 'Call Provider Usage Log',
                'verbose_name_plural': 'Call Provider Usage Logs',
                'db_table': 'call_provider_usage_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='CallProviderTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(help_text='Destination phone number used for test', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='API response time in seconds', null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='call_provider.callproviderconfig')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Provider Test Result',
                'verbose_name_plural': 'Call Provider Test Results',
                'db_table': 'call_provider_test_results',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='CallProviderHealthLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_connected', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(default=0.0, help_text='Response time in seconds')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('test_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_call_health_logs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_call_health_logs', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='call_provider.callproviderconfig')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_call_health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Provider Health Log',
                'verbose_name_plural': 'Call Provider Health Logs',
                'db_table': 'call_provider_health_logs',
                'ordering': ['-checked_at'],
            },
        ),
    ]
