# Generated by Django 4.2.17 on 2025-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_provider', '0002_callprovidertestresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callproviderhealthlog',
            name='is_connected',
        ),
        migrations.AddField(
            model_name='callproviderhealthlog',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
    ]
