# Generated by Django 4.2.17 on 2026-01-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_provider', '0003_remove_callproviderhealthlog_is_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callproviderconfig',
            name='features',
            field=models.JSONField(default=dict, help_text="Provider feature support based on plan. Example: {'call_recording': true, 'max_concurrent_calls': 20, 'call_duration_limit': 3600, 'call_analytics': true}"),
        ),
    ]
