# Generated by Django 4.2.17 on 2026-01-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_provider', '0004_callproviderconfig_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callproviderconfig',
            name='features',
        ),
    ]
