# Generated by Django 5.2.6 on 2025-09-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='template_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Variables used in template'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True, help_text='Email provider used'),
        ),
    ]
