# Generated by Django 4.2.7 on 2025-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_operations', '0003_fix_id_field_type'),
    ]

    operations = [
        # Drop and recreate email_messages table with AutoField
        migrations.RunSQL(
            """
            -- Create new table with AutoField
            CREATE TABLE email_messages_new (
                id SERIAL PRIMARY KEY,
                message_id VARCHAR(255) UNIQUE,
                to_email VARCHAR(254) NOT NULL,
                cc_emails JSONB DEFAULT '[]',
                bcc_emails JSONB DEFAULT '[]',
                from_email VARCHAR(254),
                from_name VARCHAR(100),
                reply_to VARCHAR(254),
                subject VARCHAR(500),
                html_content TEXT,
                text_content TEXT,
                template_id VARCHAR(100),
                template_name VARCHAR(100),
                template_variables JSONB DEFAULT '{}',
                priority VARCHAR(20) DEFAULT 'normal',
                status VARCHAR(20) DEFAULT 'pending',
                scheduled_at TIMESTAMPTZ,
                sent_at TIMESTAMPTZ,
                campaign_id VARCHAR(100),
                tags JSONB DEFAULT '[]',
                provider_name VARCHAR(100),
                provider_message_id VARCHAR(255),
                error_message TEXT,
                retry_count INTEGER DEFAULT 0,
                max_retries INTEGER DEFAULT 3,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW(),
                created_by_id INTEGER REFERENCES users_user(id),
                updated_by_id INTEGER REFERENCES users_user(id),
                is_deleted BOOLEAN DEFAULT FALSE,
                deleted_at TIMESTAMPTZ,
                deleted_by_id INTEGER REFERENCES users_user(id)
            );
            
            -- Copy data from old table to new table
            INSERT INTO email_messages_new (
                message_id, to_email, cc_emails, bcc_emails, from_email, from_name, 
                reply_to, subject, html_content, text_content, template_id, template_name,
                template_variables, priority, status, scheduled_at, sent_at, campaign_id,
                tags, provider_name, provider_message_id, error_message, retry_count,
                max_retries, created_at, updated_at, created_by_id, updated_by_id,
                is_deleted, deleted_at, deleted_by_id
            )
            SELECT 
                message_id, to_email, cc_emails, bcc_emails, from_email, from_name,
                reply_to, subject, html_content, text_content, template_id, template_name,
                template_variables, priority, status, scheduled_at, sent_at, campaign_id,
                tags, provider_name, provider_message_id, error_message, retry_count,
                max_retries, created_at, updated_at, created_by_id, updated_by_id,
                is_deleted, deleted_at, deleted_by_id
            FROM email_messages;
            
            -- Drop old table and rename new table
            DROP TABLE email_messages CASCADE;
            ALTER TABLE email_messages_new RENAME TO email_messages;
            """,
            reverse_sql="-- This migration cannot be easily reversed"
        ),
        
        # Drop and recreate email_queue table
        migrations.RunSQL(
            """
            -- Drop the existing table completely
            DROP TABLE IF EXISTS email_queue CASCADE;
            
            -- Create new table with AutoField
            CREATE TABLE email_queue (
                id SERIAL PRIMARY KEY,
                email_message_id INTEGER REFERENCES email_messages(id) ON DELETE CASCADE,
                priority VARCHAR(20) DEFAULT 'normal',
                status VARCHAR(20) DEFAULT 'queued',
                scheduled_for TIMESTAMPTZ NOT NULL,
                last_error TEXT,
                retry_count INTEGER DEFAULT 0,
                max_retries INTEGER DEFAULT 3,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
            """,
            reverse_sql="-- This migration cannot be easily reversed"
        ),
        
        # Drop and recreate email_tracking table
        migrations.RunSQL(
            """
            -- Drop the existing table completely
            DROP TABLE IF EXISTS email_tracking CASCADE;
            
            -- Create new table with AutoField
            CREATE TABLE email_tracking (
                id SERIAL PRIMARY KEY,
                email_message_id INTEGER REFERENCES email_messages(id) ON DELETE CASCADE,
                event_type VARCHAR(50) NOT NULL,
                event_data JSONB DEFAULT '{}',
                ip_address INET,
                user_agent TEXT,
                location VARCHAR(100),
                link_url TEXT,
                link_text VARCHAR(255),
                event_time TIMESTAMPTZ DEFAULT NOW()
            );
            """,
            reverse_sql="-- This migration cannot be easily reversed"
        ),
        
        # Drop and recreate email_delivery_reports table
        migrations.RunSQL(
            """
            -- Drop the existing table completely
            DROP TABLE IF EXISTS email_delivery_reports CASCADE;
            
            -- Create new table with AutoField
            CREATE TABLE email_delivery_reports (
                id SERIAL PRIMARY KEY,
                email_message_id INTEGER REFERENCES email_messages(id) ON DELETE CASCADE,
                provider_name VARCHAR(100) NOT NULL,
                provider_message_id VARCHAR(255) NOT NULL,
                status VARCHAR(50) NOT NULL,
                status_message TEXT,
                response_time FLOAT,
                reported_at TIMESTAMPTZ DEFAULT NOW()
            );
            """,
            reverse_sql="-- This migration cannot be easily reversed"
        ),
        
        # Drop and recreate email_analytics table
        migrations.RunSQL(
            """
            -- Drop the existing table completely
            DROP TABLE IF EXISTS email_analytics CASCADE;
            
            -- Create new table with AutoField
            CREATE TABLE email_analytics (
                id SERIAL PRIMARY KEY,
                date DATE NOT NULL,
                period_type VARCHAR(20) DEFAULT 'daily',
                total_emails INTEGER DEFAULT 0,
                sent_emails INTEGER DEFAULT 0,
                delivered_emails INTEGER DEFAULT 0,
                opened_emails INTEGER DEFAULT 0,
                clicked_emails INTEGER DEFAULT 0,
                bounced_emails INTEGER DEFAULT 0,
                complained_emails INTEGER DEFAULT 0,
                unsubscribed_emails INTEGER DEFAULT 0,
                campaign_id VARCHAR(100),
                template_id VARCHAR(100),
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
            """,
            reverse_sql="-- This migration cannot be easily reversed"
        ),
    ]
