# Generated by Django 5.2.6 on 2025-09-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_operations', '0004_change_id_to_autofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailanalytics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emaildeliveryreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
