# Generated by Django 5.2.6 on 2025-09-19 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_operations', '0005_alter_emailanalytics_id_alter_emaildeliveryreport_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='email_messa_to_emai_3e76ae_idx',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='to_email',
            new_name='to_emails',
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['to_emails', 'status'], name='email_messa_to_emai_76b2f8_idx'),
        ),
    ]
