# Generated by Django 4.2.7 on 2025-08-07 05:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renewals', '0008_fix_renewed_status_constraint'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPolicyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_tenure', models.IntegerField(help_text='Preferred policy tenure in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('coverage_type', models.CharField(choices=[('basic', 'Basic Coverage'), ('standard', 'Standard Coverage'), ('comprehensive', 'Comprehensive Coverage'), ('premium', 'Premium Coverage'), ('custom', 'Custom Coverage')], default='standard', help_text='Preferred coverage type', max_length=50)),
                ('preferred_insurer', models.CharField(blank=True, help_text='Preferred insurance company', max_length=100)),
                ('add_ons', models.JSONField(blank=True, default=dict, help_text='Additional coverage add-ons and preferences')),
                ('payment_mode', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('one_time', 'One Time'), ('installments', 'Installments')], default='annual', help_text='Preferred payment mode', max_length=50)),
                ('auto_renewal', models.BooleanField(default=False, help_text='Whether customer prefers auto-renewal')),
                ('digital_policy', models.BooleanField(default=True, help_text='Whether customer prefers digital policy documents')),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('postal', 'Postal Mail')], default='email', help_text='Preferred communication method', max_length=20)),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget for premium', max_digits=10, null=True)),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget for premium', max_digits=10, null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or notes')),
                ('created_vy', models.IntegerField(blank=True, help_text='Created by year for tracking purposes', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this preference belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policy_preferences', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('renewal_cases', models.ForeignKey(help_text='Renewal case this preference is for', on_delete=django.db.models.deletion.CASCADE, related_name='policy_preferences', to='renewals.renewalcase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_policy_preferences',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_po_custome_b51ca5_idx'), models.Index(fields=['renewal_cases'], name='customer_po_renewal_3f0876_idx'), models.Index(fields=['coverage_type'], name='customer_po_coverag_b60264_idx'), models.Index(fields=['preferred_insurer'], name='customer_po_preferr_ca1d97_idx'), models.Index(fields=['payment_mode'], name='customer_po_payment_f7f9d3_idx'), models.Index(fields=['auto_renewal'], name='customer_po_auto_re_662efd_idx'), models.Index(fields=['created_vy'], name='customer_po_created_7819b6_idx')],
                'unique_together': {('customer', 'renewal_cases')},
            },
        ),
    ]
