# Generated by Django 5.2.7 on 2025-11-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_policy_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolicypreference',
            name='avoided_policy_types',
            field=models.CharField(blank=True, help_text="Policy types the customer prefers to avoid (e.g., 'ULIP, Endowment')", max_length=255),
        ),
    ]
