# Generated by Django 4.2.7 on 2025-07-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagevariant',
            name='original_file',
            field=models.ForeignKey(limit_choices_to={'mime_type__startswith': 'image/'}, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='uploads.fileupload'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='uploads.fileupload'),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileprocessingqueue',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='uploads.fileupload'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['session_id'], name='uploads_upl_session_7e7e51_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['created_by', 'is_completed'], name='uploads_upl_created_ce44a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagevariant',
            unique_together={('original_file', 'variant_type')},
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['category', 'status'], name='uploads_fil_categor_0a1734_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['created_by', 'category'], name='uploads_fil_created_d96818_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_hash'], name='uploads_fil_file_ha_2b9fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['expires_at'], name='uploads_fil_expires_cc67df_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['share_token'], name='uploads_fil_share_t_4408fb_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['expires_at'], name='uploads_fil_expires_a1f256_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingqueue',
            index=models.Index(fields=['status', 'priority'], name='uploads_fil_status_c3fcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingqueue',
            index=models.Index(fields=['task_type', 'status'], name='uploads_fil_task_ty_bab977_idx'),
        ),
    ]
