# Generated by Django 4.2.7 on 2025-10-16 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel File'), ('csv', 'CSV File'), ('json', 'JSON File'), ('xml', 'XML File')], max_length=10)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('file_path', models.CharField(help_text='Path to uploaded file', max_length=500)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='uploading', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Total records in file')),
                ('successful_records', models.PositiveIntegerField(default=0, help_text='Successfully processed records')),
                ('failed_records', models.PositiveIntegerField(default=0, help_text='Failed to process records')),
                ('skipped_records', models.PositiveIntegerField(default=0, help_text='Skipped records')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, help_text='Total processing time', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='Validation errors found')),
                ('processing_result', models.JSONField(blank=True, default=dict, help_text='Processing results and statistics')),
                ('created_objects', models.JSONField(blank=True, default=dict, help_text='Objects created during processing')),
                ('updated_objects', models.JSONField(blank=True, default=dict, help_text='Objects updated during processing')),
                ('upload_session_id', models.CharField(blank=True, help_text='Upload session identifier', max_length=100)),
                ('batch_id', models.CharField(blank=True, help_text='Batch processing identifier', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('notify_on_completion', models.BooleanField(default=True, help_text='Send notification when processing completes')),
                ('notify_email', models.EmailField(blank=True, help_text='Email to send notifications to', max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploads_uploadfile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='uploads_upl_status_3204cd_idx'), models.Index(fields=['file_type', 'status'], name='uploads_upl_file_ty_17bf44_idx'), models.Index(fields=['upload_session_id'], name='uploads_upl_upload__8b4881_idx'), models.Index(fields=['batch_id'], name='uploads_upl_batch_i_fb0618_idx')],
            },
        ),
    ]
