# Generated by Django 5.2.7 on 2025-11-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Star this message in the UI'),
        ),
        migrations.AlterModelTable(
            name='whatsappmessage',
            table='whatsapp_manager_messages',
        ),
    ]
