# Generated by Django 5.2.7 on 2025-12-24 06:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0001_initial'),
    ]

    operations = []
