# Generated by Django 4.2.7 on 2025-09-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0012_remove_priority_column'),
        ('case_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='case',
            field=models.ForeignKey(help_text='Case this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='case_comments', to='renewals.renewalcase'),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='case',
            field=models.ForeignKey(help_text='Case this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='renewals.renewalcase'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
