# Generated by Django 4.2.7 on 2025-11-06 09:29

from django.db import migrations, connection


def delete_casecomment_table(apps, schema_editor):
    """Delete the case_history_casecomment table and related foreign keys"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'case_history'
            );
        """)
        case_history_exists = cursor.fetchone()[0]
        
        if case_history_exists:
            cursor.execute("""
                DO $$
                DECLARE
                    r RECORD;
                BEGIN
                    FOR r IN (
                        SELECT constraint_name
                        FROM information_schema.table_constraints
                        WHERE constraint_type = 'FOREIGN KEY'
                            AND table_name = 'case_history'
                            AND constraint_name LIKE '%related_comment%'
                    ) LOOP
                        EXECUTE 'ALTER TABLE case_history DROP CONSTRAINT IF EXISTS ' || r.constraint_name || ' CASCADE;';
                    END LOOP;
                END
                $$;
            """)
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'case_history_casecomment'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            cursor.execute("DROP TABLE IF EXISTS case_history_casecomment CASCADE;")


def reverse_delete_casecomment_table(apps, schema_editor):
    """Reverse operation - table recreation not needed as we're deleting it"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0002_alter_casecomment_case_alter_casehistory_case_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    delete_casecomment_table,
                    reverse_code=reverse_delete_casecomment_table
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='casehistory',
                    name='related_comment',
                ),
                migrations.DeleteModel(
                    name='CaseComment',
                ),
            ],
        ),
    ]
