# Generated by Django 4.2.7 on 2025-09-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_remove_customer_communication_preferences'),
        ('customer_communication_preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('postal_mail', 'Postal Mail'), ('in_app', 'In-App Notification'), ('push_notification', 'Push Notification')], help_text='Communication channel used', max_length=20)),
                ('communication_date', models.DateTimeField(help_text='Date and time of communication attempt')),
                ('outcome', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('no_response', 'No Response'), ('busy', 'Busy'), ('invalid_number', 'Invalid Number'), ('blocked', 'Blocked'), ('opt_out', 'Opted Out'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied')], help_text='Result of the communication attempt', max_length=20)),
                ('message_content', models.TextField(blank=True, help_text='Content of the message sent (optional)')),
                ('response_received', models.TextField(blank=True, help_text='Customer response if any (optional)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the communication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this communication was sent to', on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated this communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_communications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communication_logs',
                'ordering': ['-communication_date'],
                'indexes': [models.Index(fields=['customer', 'communication_date'], name='communicati_custome_503115_idx'), models.Index(fields=['channel', 'outcome'], name='communicati_channel_87778d_idx'), models.Index(fields=['communication_date'], name='communicati_communi_691435_idx')],
            },
        ),
    ]
