# Generated by Django 5.2.7 on 2025-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_communication_preferences', '0002_create_communication_logs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='duration_in_minutes',
            field=models.IntegerField(blank=True, help_text='Duration of the call/interaction in minutes', null=True),
        ),
    ]
