# Generated by Django 5.2.7 on 2025-11-10 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Policy Holders - Expiring Q4', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the audience criteria.')),
                ('segments', models.JSONField(default=list, help_text='List of comma-separated segments/tags (e.g., High Value, Auto Insurance)')),
                ('contact_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra metadata, e.g., uploaded file hashes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audiences', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_audiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audience',
                'verbose_name_plural': 'Audiences',
                'db_table': 'audience_manager_audiences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AudienceContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Primary email address for campaigning', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='audience_manager.audience')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audience_contacts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_audience_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audience Contact',
                'verbose_name_plural': 'Audience Contacts',
                'db_table': 'audience_manager_contacts',
                'ordering': ['name'],
                'unique_together': {('audience', 'email')},
            },
        ),
    ]
