# Generated by Django 5.2.7 on 2025-11-13 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiencecontact',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='audiencecontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address for campaigning', max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='audiencecontact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('audience', 'email'), name='unique_email_per_audience'),
        ),
        migrations.AddConstraint(
            model_name='audiencecontact',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('audience', 'phone'), name='unique_phone_per_audience'),
        ),
    ]
