# Generated by Django 5.2.7 on 2025-11-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience_manager', '0002_alter_audiencecontact_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencecontact',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Policy expiry date', null=True),
        ),
    ]
