# Generated by Django 4.2.7 on 2025-09-06 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])]),
        ),
    ]
