# Generated by Django 4.2.7 on 2025-11-05 06:31
# Modified to handle existing claims table

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def add_missing_columns_if_needed(apps, schema_editor):
    """Add missing columns to existing claims table if they don't exist"""
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'claims'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            # Table doesn't exist, let Django create it normally
            return
        
        # Table exists, check and add missing columns
        # Check existing columns
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'claims'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Add missing BaseModel columns if they don't exist
        if 'created_at' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW();")
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_created_at_idx ON claims(created_at);")
        
        if 'updated_at' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();")
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_updated_at_idx ON claims(updated_at);")
        
        if 'is_deleted' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;")
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_is_deleted_idx ON claims(is_deleted);")
        
        if 'deleted_at' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN deleted_at TIMESTAMPTZ;")
        
        # Add missing foreign key columns if they don't exist
        if 'created_by_id' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN created_by_id INTEGER;")
        
        if 'updated_by_id' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN updated_by_id INTEGER;")
        
        if 'deleted_by_id' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN deleted_by_id INTEGER;")
        
        # Add new fields requested by user
        if 'insurance_company_name' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN insurance_company_name VARCHAR(200) DEFAULT '';")
        
        if 'policy_number' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN policy_number VARCHAR(100) DEFAULT '';")
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_policy_number_idx ON claims(policy_number);")
        
        if 'expire_date' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN expire_date DATE;")
        
        if 'remarks' not in existing_columns:
            cursor.execute("ALTER TABLE claims ADD COLUMN remarks TEXT DEFAULT '';")
        
        # Add foreign key constraints if they don't exist
        try:
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'claims_created_by_id_fkey'
                    ) THEN
                        ALTER TABLE claims ADD CONSTRAINT claims_created_by_id_fkey
                            FOREIGN KEY (created_by_id) REFERENCES users_user(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """)
        except Exception:
            pass
        
        try:
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'claims_updated_by_id_fkey'
                    ) THEN
                        ALTER TABLE claims ADD CONSTRAINT claims_updated_by_id_fkey
                            FOREIGN KEY (updated_by_id) REFERENCES users_user(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """)
        except Exception:
            pass
        
        try:
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'claims_deleted_by_id_fkey'
                    ) THEN
                        ALTER TABLE claims ADD CONSTRAINT claims_deleted_by_id_fkey
                            FOREIGN KEY (deleted_by_id) REFERENCES users_user(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """)
        except Exception:
            pass
        
        # Add indexes if they don't exist
        try:
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_claim_n_b9e177_idx ON claims(claim_number);")
        except Exception:
            pass
        
        try:
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_custome_e8d438_idx ON claims(customer_id, status);")
        except Exception:
            pass
        
        try:
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_policy__a9ba66_idx ON claims(policy_id, status);")
        except Exception:
            pass
        
        try:
            cursor.execute("CREATE INDEX IF NOT EXISTS claims_status_cb731f_idx ON claims(status);")
        except Exception:
            pass


def reverse_add_missing_columns(apps, schema_editor):
    """Reverse migration - not easily reversible, so we'll just pass"""
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_rename_customers_cu_channel_123abc_idx_customers_c_channel_d1da5f_idx'),
        ('policies', '0009_claimtimelineevent'),
    ]

    operations = [
        # First, add missing columns to existing table if it exists
        migrations.RunPython(
            add_missing_columns_if_needed,
            reverse_add_missing_columns,
        ),
        # Use SeparateDatabaseAndState to handle existing table
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations - check if table exists, if not create it
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT FROM information_schema.tables 
                            WHERE table_name = 'claims'
                        ) THEN
                            -- Table doesn't exist, create it
                            CREATE TABLE claims (
                                id SERIAL PRIMARY KEY,
                                created_at TIMESTAMPTZ DEFAULT NOW(),
                                updated_at TIMESTAMPTZ DEFAULT NOW(),
                                is_deleted BOOLEAN DEFAULT FALSE,
                                deleted_at TIMESTAMPTZ,
                                claim_number VARCHAR(100) UNIQUE NOT NULL,
                                claim_type VARCHAR(50) NOT NULL,
                                claim_amount NUMERIC(12,2) NOT NULL,
                                description TEXT NOT NULL,
                                status VARCHAR(20) DEFAULT 'submitted',
                                insurance_company_name VARCHAR(200) DEFAULT '',
                                policy_number VARCHAR(100) DEFAULT '',
                                expire_date DATE,
                                remarks TEXT DEFAULT '',
                                created_by_id INTEGER REFERENCES users_user(id) ON DELETE SET NULL,
                                customer_id INTEGER NOT NULL REFERENCES customers_customer(id) ON DELETE CASCADE,
                                deleted_by_id INTEGER REFERENCES users_user(id) ON DELETE SET NULL,
                                policy_id INTEGER REFERENCES policies_policy(id) ON DELETE SET NULL,
                                updated_by_id INTEGER REFERENCES users_user(id) ON DELETE SET NULL
                            );
                            
                            CREATE INDEX claims_claim_n_b9e177_idx ON claims(claim_number);
                            CREATE INDEX claims_custome_e8d438_idx ON claims(customer_id, status);
                            CREATE INDEX claims_policy__a9ba66_idx ON claims(policy_id, status);
                            CREATE INDEX claims_status_cb731f_idx ON claims(status);
                            CREATE INDEX claims_created_at_idx ON claims(created_at);
                            CREATE INDEX claims_updated_at_idx ON claims(updated_at);
                            CREATE INDEX claims_is_deleted_idx ON claims(is_deleted);
                        END IF;
                    END $$;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS claims CASCADE;"
                ),
            ],
            state_operations=[
                # State operations - always create the model in Django state
                migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim_number', models.CharField(db_index=True, help_text='Auto-generated claim number in format CLM0001', max_length=100, unique=True)),
                ('claim_type', models.CharField(choices=[('death', 'Death Claim'), ('maturity', 'Maturity Claim'), ('surrender', 'Surrender'), ('partial_withdrawal', 'Partial Withdrawal'), ('accident', 'Accident'), ('medical', 'Medical'), ('disability', 'Disability'), ('other', 'Other')], help_text='Type of claim', max_length=50)),
                ('claim_amount', models.DecimalField(decimal_places=2, help_text='Claim amount', max_digits=12)),
                ('description', models.TextField(help_text='Description of the claim')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('closed', 'Closed')], db_index=True, default='submitted', help_text='Current status of the claim', max_length=20)),
                ('insurance_company_name', models.CharField(blank=True, help_text='Name of the insurance company', max_length=200)),
                ('policy_number', models.CharField(blank=True, db_index=True, help_text='Policy number', max_length=100)),
                ('expire_date', models.DateField(blank=True, help_text='Policy expiration date', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customer_id', help_text='Customer associated with this claim', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, db_column='policy_id', help_text='Policy associated with this claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_records', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim_number'], name='claims_claim_n_b9e177_idx'), models.Index(fields=['customer', 'status'], name='claims_custome_e8d438_idx'), models.Index(fields=['policy', 'status'], name='claims_policy__a9ba66_idx'), models.Index(fields=['status'], name='claims_status_cb731f_idx')],
            },
        ),
            ],
        ),
    ]
