# Generated by Django 4.2.7 on 2025-11-05 06:43
# Modified to handle existing data and update constraint

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        # Step 1: Update existing rows with old status values to new valid statuses
        migrations.RunSQL(
            """
            UPDATE claims 
            SET status = CASE 
                WHEN status = 'submitted' THEN 'pending'
                WHEN status = 'under_review' THEN 'in_progress'
                WHEN status = 'paid' THEN 'settled'
                WHEN status = 'closed' THEN 'settled'
                WHEN status = 'approved' THEN 'approved'
                WHEN status = 'rejected' THEN 'rejected'
                ELSE 'pending'
            END
            WHERE status NOT IN (
                'pending', 'in_progress', 'document_pending', 
                'approved', 'settled', 'rejected'
            );
            """,
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Step 2: Drop the existing constraint if it exists
        migrations.RunSQL(
            "ALTER TABLE claims DROP CONSTRAINT IF EXISTS claims_status_check;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Step 3: Alter the field
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('document_pending', 'Document Pending'), ('approved', 'Approved'), ('settled', 'Settled'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the claim', max_length=20),
        ),
        
        # Step 4: Recreate the constraint with the new status choices
        migrations.RunSQL(
            """
            ALTER TABLE claims ADD CONSTRAINT claims_status_check 
            CHECK (status IN (
                'pending', 'in_progress', 'document_pending', 
                'approved', 'settled', 'rejected'
            ));
            """,
            reverse_sql="ALTER TABLE claims DROP CONSTRAINT IF EXISTS claims_status_check;"
        ),
    ]
