# Generated by Django 4.2.7 on 2025-11-05 07:23
# Modified to handle existing incident_date column in database

from django.db import migrations, models, connection


def make_incident_date_nullable(apps, schema_editor):
    """Make incident_date column nullable if it exists and is NOT NULL"""
    with connection.cursor() as cursor:
        # Check if column exists and if it's NOT NULL
        cursor.execute("""
            SELECT is_nullable 
            FROM information_schema.columns 
            WHERE table_name = 'claims' AND column_name = 'incident_date'
        """)
        result = cursor.fetchone()
        
        if result and result[0] == 'NO':
            # Column exists and is NOT NULL, make it nullable
            cursor.execute("""
                ALTER TABLE claims 
                ALTER COLUMN incident_date DROP NOT NULL;
            """)


def reverse_make_incident_date_nullable(apps, schema_editor):
    """Reverse operation - make incident_date NOT NULL (optional)"""
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT is_nullable 
            FROM information_schema.columns 
            WHERE table_name = 'claims' AND column_name = 'incident_date'
        """)
        result = cursor.fetchone()
        
        if result and result[0] == 'YES':
            # Set default value for existing NULL rows before making NOT NULL
            cursor.execute("""
                UPDATE claims 
                SET incident_date = created_at::date 
                WHERE incident_date IS NULL;
            """)
            cursor.execute("""
                ALTER TABLE claims 
                ALTER COLUMN incident_date SET NOT NULL;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_add_policy_number_column'),
    ]

    operations = [
        # Step 1: Make existing incident_date column nullable if it exists
        migrations.RunPython(
            make_incident_date_nullable,
            reverse_code=reverse_make_incident_date_nullable
        ),
        # Step 2: Add field to Django model (will be no-op if column already exists)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operation needed - column already exists
            ],
            state_operations=[
                migrations.AddField(
                    model_name='claim',
                    name='incident_date',
                    field=models.DateField(blank=True, help_text='Date when the incident occurred', null=True),
                ),
            ]
        ),
    ]
