# Generated by Django 5.2.7 on 2025-12-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_ensure_customer_foreign_key_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='The date and time the event occurred.')),
                ('title', models.CharField(help_text="Short title of the event (e.g., 'Surveyor Assigned').", max_length=150)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event or action taken.')),
                ('claim', models.ForeignKey(help_text='The claim this timeline event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='claims.claim')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
