# Generated by Django 5.2.7 on 2025-12-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name of the flow', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('entry_point', models.CharField(choices=[('INBOUND', 'Inbound Message Trigger'), ('POST_CAMPAIGN', 'Post-Campaign Follow-up'), ('SCHEDULED', 'Scheduled Trigger'), ('API', 'API Trigger')], default='INBOUND', max_length=50)),
                ('canvas_layout', models.JSONField(default=dict, help_text='The visual arrangement (x, y coordinates) and connections between blocks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=50)),
                ('block_type', models.CharField(choices=[('SEND_MESSAGE', 'Send Message'), ('COLLECT_INPUT', 'Collect Input'), ('BUTTONS', 'Buttons'), ('CAROUSEL', 'Carousel'), ('API_CALL', 'API Call'), ('CONDITIONAL_LOGIC', 'Conditional Logic'), ('HUMAN_HANDOVER', 'Human Handover'), ('TEMPLATE', 'Use Template'), ('FLOW_LAUNCH', 'WhatsApp Flow')], max_length=50)),
                ('configuration', models.JSONField(default=dict)),
                ('connections', models.JSONField(default=list)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='whatsapp_flow_management.whatsappflow')),
            ],
            options={
                'db_table': 'whatsapp_flow_blocks',
                'unique_together': {('flow', 'block_id')},
            },
        ),
    ]
