# Generated by Django 5.2.7 on 2025-12-15 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('messages_delivered', models.PositiveIntegerField(default=0)),
                ('messages_replied', models.PositiveIntegerField(default=0)),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reply_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='whatsapp_flow_management.whatsappflow')),
            ],
        ),
    ]
