# Generated by Django 5.2.7 on 2025-12-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_management', '0003_flowtemplate_whatsappmessagetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowblock',
            name='block_type',
            field=models.CharField(choices=[('SEND_MESSAGE', 'Send Message'), ('COLLECT_INPUT', 'Collect Input'), ('BUTTONS', 'Buttons'), ('API_CALL', 'API Call'), ('CONDITIONAL_LOGIC', 'Conditional Logic'), ('TEMPLATE', 'Use Template')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flowtemplate',
            name='template_flow_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='whatsappflow',
            name='canvas_layout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='whatsappflow',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagetemplate',
            name='content_json',
            field=models.JSONField(default=dict),
        ),
    ]
