# Generated by Django 5.2.7 on 2025-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_management', '0006_flowtemplate_created_at_flowtemplate_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowanalytics',
            name='avg_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowanalytics',
            name='click_through_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flowanalytics',
            name='completed_runs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
