# Generated by Django 5.2.7 on 2025-12-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_management', '0008_aitemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowanalytics',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
    ]
