# Generated by Django 5.2.7 on 2025-12-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_management', '0009_flowanalytics_total_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowanalytics',
            name='avg_duration_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowanalytics',
            name='dropped_off_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowanalytics',
            name='node_drop_off_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='flowanalytics',
            name='completed_runs',
            field=models.IntegerField(default=0),
        ),
    ]
