# Generated by Django 5.2.7 on 2025-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_management', '0010_flowanalytics_avg_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappflow',
            name='entry_point',
            field=models.CharField(choices=[('INBOUND', 'Inbound Message Trigger'), ('POST_CAMPAIGN', 'Post-Campaign Follow-up'), ('SCHEDULED', 'Scheduled Trigger'), ('API', 'API Trigger'), ('WEBHOOK', 'Webhook Trigger')], default='INBOUND', max_length=50),
        ),
    ]
