# Generated by Django 4.2.7 on 2025-08-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyBeneficiary',
        ),
    ]
