# Generated by Django 5.2.6 on 2025-09-12 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_communication_preferences'),
        ('policies', '0004_policybeneficiary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Full name of the policy member', max_length=200)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], help_text='Relationship to the primary customer', max_length=20)),
                ('dob', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10)),
                ('sum_insured', models.DecimalField(decimal_places=2, help_text='Sum insured amount for this member', max_digits=15)),
                ('premium_share', models.DecimalField(decimal_places=2, help_text='Premium amount for this member', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Primary customer who owns the policy', on_delete=django.db.models.deletion.CASCADE, related_name='policy_members', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Policy this member is covered under', on_delete=django.db.models.deletion.CASCADE, related_name='policy_members', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_members',
                'ordering': ['relation', 'name'],
                'indexes': [models.Index(fields=['customer', 'policy'], name='policy_memb_custome_dfba26_idx'), models.Index(fields=['policy', 'relation'], name='policy_memb_policy__3ac5fd_idx'), models.Index(fields=['relation'], name='policy_memb_relatio_e98213_idx')],
                'unique_together': {('policy', 'name', 'relation')},
            },
        ),
    ]
