# Generated by Django 5.2.6 on 2025-09-12 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_communication_preferences'),
        ('policies', '0005_policymember'),
        ('renewals', '0009_remove_renewalcase_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policymember',
            name='renewal_case',
            field=models.ForeignKey(blank=True, help_text='Renewal case this member belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_members', to='renewals.renewalcase'),
        ),
        migrations.AddIndex(
            model_name='policymember',
            index=models.Index(fields=['renewal_case'], name='policy_memb_renewal_4070e3_idx'),
        ),
    ]
