# Generated by Django 4.2.7 on 2025-09-23 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0006_add_renewal_case_to_policy_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agent_code', models.CharField(help_text='Auto-generated agent code', max_length=50, unique=True)),
                ('agent_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_agents',
                'ordering': ['agent_name'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Policy agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policies.policyagent'),
        ),
        migrations.AddIndex(
            model_name='policyagent',
            index=models.Index(fields=['agent_code'], name='policy_agen_agent_c_7b00f9_idx'),
        ),
        migrations.AddIndex(
            model_name='policyagent',
            index=models.Index(fields=['agent_name'], name='policy_agen_agent_n_abb6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='policyagent',
            index=models.Index(fields=['is_active'], name='policy_agen_is_acti_a300b6_idx'),
        ),
    ]
