# Generated by Django 4.2.7 on 2025-09-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_create_policy_agents_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='agent_code',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='agent_name',
        ),
    ]
