# Generated by Django 5.2.7 on 2025-12-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailprovidertestresult',
            options={'verbose_name': 'Email Provider Test Result', 'verbose_name_plural': 'Email Provider Test Results'},
        ),
        migrations.RemoveField(
            model_name='emailprovidertestresult',
            name='tested_at',
        ),
    ]
