# Generated by Django 5.2.7 on 2025-12-10 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0002_alter_emailprovidertestresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailprovidertestresult',
            options={'ordering': ['-tested_at'], 'verbose_name': 'Email Provider Test Result', 'verbose_name_plural': 'Email Provider Test Results'},
        ),
        migrations.AddField(
            model_name='emailprovidertestresult',
            name='tested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
