# Generated by Django 4.2.7 on 2025-10-28 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedCaseChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Unique identifier for the closed case', max_length=100, unique=True)),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=255)),
                ('policy_number', models.CharField(help_text='Policy number associated with the case', max_length=100)),
                ('product_name', models.CharField(help_text='Insurance product name', max_length=255)),
                ('category', models.CharField(help_text='Insurance category (Life, Motor, Health, etc.)', max_length=50)),
                ('mobile_number', models.CharField(help_text='Customer mobile number', max_length=15)),
                ('language', models.CharField(default='English', help_text='Preferred language for communication', max_length=20)),
                ('profile_type', models.CharField(choices=[('Normal', 'Normal'), ('HNI', 'High Net Worth Individual')], default='Normal', help_text='Customer profile type', max_length=20)),
                ('chatbot_session_id', models.CharField(help_text='Unique session ID for chatbot interaction', max_length=255, unique=True)),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last time customer interacted with chatbot')),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Number of interactions with chatbot')),
                ('is_active', models.BooleanField(default=True, help_text='Whether chatbot is active for this case')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Closed Case Chatbot',
                'verbose_name_plural': 'Closed Case Chatbots',
                'db_table': 'closed_case_chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClosedCaseChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], help_text='Type of message', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on message helpfulness', null=True)),
                ('chatbot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='closed_case_chatbot.closedcasechatbot')),
            ],
            options={
                'verbose_name': 'Chatbot Message',
                'verbose_name_plural': 'Chatbot Messages',
                'db_table': 'closed_case_chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClosedCaseChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='Name of the metric', max_length=100)),
                ('metric_value', models.FloatField(help_text='Value of the metric')),
                ('metric_date', models.DateField(help_text='Date when metric was recorded')),
                ('chatbot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='closed_case_chatbot.closedcasechatbot')),
            ],
            options={
                'verbose_name': 'Chatbot Analytics',
                'verbose_name_plural': 'Chatbot Analytics',
                'db_table': 'closed_case_chatbot_analytics',
                'ordering': ['-metric_date'],
            },
        ),
    ]
