# Generated by Django 5.2.6 on 2025-11-25 07:04

import apps.whatsapp_provider.models
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('whatsapp_provider', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='whatsappaccountusagelog',
            name='date',
            field=models.DateField(default=apps.whatsapp_provider.models.today_date),
        ),
        migrations.AlterField(
            model_name='whatsappprovider',
            name='last_reset_daily',
            field=models.DateField(default=apps.whatsapp_provider.models.today_date),
        ),
        migrations.AlterField(
            model_name='whatsappprovider',
            name='last_reset_monthly',
            field=models.DateField(default=apps.whatsapp_provider.models.today_date),
        ),
    ]
