# Generated by Django 5.2.7 on 2025-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0002_alter_whatsappaccountusagelog_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whatsappphonenumber',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='credentials',
        ),
        migrations.AddField(
            model_name='whatsappprovider',
            name='access_token',
            field=models.CharField(blank=True, help_text='The secret key/token (Encrypted)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsappprovider',
            name='account_id',
            field=models.CharField(blank=True, help_text='The account identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappprovider',
            name='api_url',
            field=models.CharField(blank=True, help_text='API Endpoint URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappprovider',
            name='api_version',
            field=models.CharField(blank=True, default='v18.0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='whatsappprovider',
            name='app_id',
            field=models.CharField(blank=True, help_text='App ID or App Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappprovider',
            name='phone_number_id',
            field=models.CharField(blank=True, help_text='The identifier for the phone number', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='whatsappphonenumber',
            name='provider',
        ),
    ]
