# Generated by Django 5.2.7 on 2025-11-26 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0003_alter_whatsappphonenumber_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='whatsapp_provider.whatsappprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappphonenumber',
            unique_together={('provider', 'phone_number_id')},
        ),
    ]
