# Generated by Django 5.2.7 on 2025-11-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0004_whatsappphonenumber_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='phone_number_id',
        ),
        migrations.AlterField(
            model_name='whatsappprovider',
            name='provider_type',
            field=models.CharField(choices=[('meta', 'Meta Business API'), ('twilio', 'Twilio WhatsApp'), ('gupshup', 'Gupshup WhatsApp'), ('360dialog', '360Dialog')], max_length=20),
        ),
    ]
