# Generated by Django 5.2.7 on 2025-11-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0006_whatsappprovider_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='phone_number_id',
        ),
    ]
