# Generated by Django 5.2.7 on 2025-11-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0008_whatsappprovider_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='api_version',
        ),
    ]
