# Generated by Django 5.2.7 on 2025-11-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0010_whatsappprovider_api_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='api_version',
        ),
    ]
