# Generated by Django 5.2.7 on 2025-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0012_whatsappprovider_api_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappprovider',
            name='waba_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
