# Generated by Django 5.2.7 on 2025-11-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0013_whatsappprovider_waba_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='waba_account_id',
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='waba_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
