# Generated by Django 5.2.7 on 2025-11-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0014_remove_whatsappprovider_waba_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappphonenumber',
            name='waba_account_id',
        ),
    ]
