# Generated by Django 5.2.7 on 2025-11-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0015_remove_whatsappphonenumber_waba_account_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whatsappmessagetemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='whatsappmessagetemplate',
            name='provider',
        ),
    ]
