# Generated by Django 5.2.7 on 2025-11-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0016_alter_whatsappmessagetemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagetemplate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='whatsapp_provider.whatsappprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappmessagetemplate',
            unique_together={('provider', 'name', 'language')},
        ),
    ]
