# Generated by Django 5.2.7 on 2025-12-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0017_whatsappmessagetemplate_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappprovider',
            name='api_version',
        ),
    ]
