# Generated by Django 5.2.7 on 2025-12-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0018_remove_whatsappprovider_api_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappprovider',
            name='api_version',
            field=models.CharField(blank=True, default='v18.0', max_length=10, null=True),
        ),
    ]
