# Generated by Django 5.2.7 on 2025-12-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0024_add_missing_related_provider_ids'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whatsappprovider',
            unique_together={('provider_type', 'account_id', 'is_deleted')},
        ),
    ]
