# Generated by Django 4.2.7 on 2025-08-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_coverages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycoverage',
            name='support_coverage',
            field=models.BooleanField(default=False, help_text='Whether this coverage includes 24/7 support services'),
        ),
    ]
