# Generated by Django 4.2.7 on 2025-08-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
        ('policy_coverages', '0002_policycoverage_support_coverage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policycoverage',
            name='policy_cove_policy__7c35eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='policycoverage',
            name='policy_cove_policy__2489b5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='policycoverage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='policycoverage',
            name='policy_type',
            field=models.ForeignKey(default=1, help_text='Policy type this coverage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policy_coverages', to='policies.policytype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='policycoverage',
            unique_together={('policy_type', 'coverage_name', 'coverage_type')},
        ),
        migrations.AddIndex(
            model_name='policycoverage',
            index=models.Index(fields=['policy_type', 'coverage_type'], name='policy_cove_policy__4628ea_idx'),
        ),
        migrations.AddIndex(
            model_name='policycoverage',
            index=models.Index(fields=['policy_type', 'is_included'], name='policy_cove_policy__ac42cc_idx'),
        ),
        migrations.RemoveField(
            model_name='policycoverage',
            name='policy',
        ),
    ]
