# Generated by Django 4.2.17 on 2025-12-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurance_type',
            field=models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('motor', 'Motor Insurance'), ('home', 'Home Insurance'), ('car', 'Car Insurance')], max_length=20),
        ),
    ]
