# Generated by Django 4.2.7 on 2025-08-11 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('feature_type', models.CharField(choices=[('vehicle_insurance', 'Vehicle Insurance'), ('life_insurance', 'Life Insurance'), ('health_insurance', 'Health Insurance'), ('home_insurance', 'Home Insurance'), ('travel_insurance', 'Travel Insurance'), ('motor_insurance', 'Motor Insurance'), ('property_insurance', 'Property Insurance'), ('general', 'General')], db_index=True, default='general', help_text='Type of insurance feature', max_length=50)),
                ('feature_name', models.CharField(help_text='Name of the policy feature', max_length=200)),
                ('feature_description', models.TextField(help_text='Detailed description of the feature')),
                ('feature_value', models.CharField(blank=True, help_text='Value or amount associated with the feature (if applicable)', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this feature is currently active')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this feature is mandatory for the policy')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this feature')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional information about the feature')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Policy this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policy_features', to='policies.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_features',
                'ordering': ['display_order', 'feature_name'],
                'indexes': [models.Index(fields=['policy', 'is_active'], name='policy_feat_policy__afccf2_idx'), models.Index(fields=['feature_type', 'is_active'], name='policy_feat_feature_4abcec_idx'), models.Index(fields=['policy', 'feature_type'], name='policy_feat_policy__ae3bf0_idx'), models.Index(fields=['display_order'], name='policy_feat_display_0751e4_idx')],
                'unique_together': {('policy', 'feature_name')},
            },
        ),
    ]
