# Generated by Django 4.2.7 on 2025-08-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
        ('policy_features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policyfeature',
            name='policy_feat_policy__afccf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='policyfeature',
            name='policy_feat_policy__ae3bf0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='policyfeature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='policyfeature',
            name='policy_type',
            field=models.ForeignKey(default=1, help_text='Policy type this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policy_features', to='policies.policytype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='policyfeature',
            unique_together={('policy_type', 'feature_name')},
        ),
        migrations.AddIndex(
            model_name='policyfeature',
            index=models.Index(fields=['policy_type', 'is_active'], name='policy_feat_policy__688f34_idx'),
        ),
        migrations.AddIndex(
            model_name='policyfeature',
            index=models.Index(fields=['policy_type', 'feature_type'], name='policy_feat_policy__dcaa5e_idx'),
        ),
        migrations.RemoveField(
            model_name='policyfeature',
            name='policy',
        ),
    ]
