# Generated by Django 4.2.7 on 2025-08-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
        ('policy_features', '0002_remove_policyfeature_policy_feat_policy__afccf2_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='policyfeature',
            unique_together={('policy_type', 'feature_name', 'feature_type')},
        ),
    ]
