# Generated by Django 4.2.7 on 2025-07-31 12:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Channel name', max_length=255)),
                ('channel_type', models.CharField(choices=[('online', 'Online'), ('mobile', 'Mobile'), ('offline', 'Offline'), ('phone', 'Phone'), ('agent', 'Agent')], help_text='Type of channel', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Channel description')),
                ('cost_per_lead', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per lead in currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Channel budget', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', help_text='Current status of the channel', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Channel priority level', max_length=10)),
                ('working_hours', models.CharField(blank=True, help_text="Working hours for the channel (e.g., '9:00 AM - 5:00 PM')", max_length=100)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity/throughput for the channel', null=True)),
            ],
            options={
                'db_table': 'channel',
                'ordering': ['name'],
            },
        ),
    ]
