# Generated by Django 4.2.7 on 2025-07-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        ('business_channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('target_audience', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Channel manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='target_audience',
            field=models.ForeignKey(blank=True, help_text='Target audience for this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='target_audience.targetaudience'
),
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type'], name='channel_channel_f61eae_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['status'], name='channel_status_3fd5af_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['priority'], name='channel_priorit_367f87_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['manager'], name='channel_manager_3e3f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['target_audience'], name='channel_target__05f03a_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.CheckConstraint(check=models.Q(('cost_per_lead__gte', 0)), name='positive_cost_per_lead'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.CheckConstraint(check=models.Q(('budget__gte', 0)), name='positive_budget'),
        ),
    ]
