# Generated by Django 4.2.7 on 2025-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_channels', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channel',
            name='channel_manager_3e3f5e_idx',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='manager',
        ),
        migrations.AddField(
            model_name='channel',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Manager name for this channel', max_length=100),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['manager_name'], name='channel_manager_2aaafd_idx'),
        ),
    ]
