# Generated by Django 4.2.7 on 2025-08-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_channels', '0004_add_customer_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channel',
            new_name='channel_custome_2776ba_idx',
            old_name='channel_customer_idx',
        ),
    ]
