# Generated by Django 4.2.7 on 2025-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_channels', '0005_rename_channel_customer_idx_channel_custome_2776ba_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Mobile', 'Mobile'), ('Offline', 'Offline'), ('Phone', 'Phone'), ('Agent', 'Agent')], help_text='Type of channel', max_length=20),
        ),
    ]
