# Generated by Django 4.2.7 on 2025-08-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_channels', '0006_alter_channel_channel_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channel',
            name='channel_custome_2776ba_idx',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='customer',
        ),
    ]
