# Generated by Django 4.2.7 on 2025-08-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('target_audience', '__first__'),
        ('business_channels', '0007_remove_channel_channel_custome_2776ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='target_audience',
            field=models.ForeignKey(blank=True, help_text='Target audience for this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='target_audience.targetaudience'),
        ),
    ]
