# Generated by Django 4.2.7 on 2025-09-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_communication_preferences'),
        ('business_channels', '0008_alter_channel_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this channel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['customer'], name='channel_custome_2776ba_idx'),
        ),
    ]
