# Generated by Django 4.2.7 on 2025-08-11 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_document_id', models.BigIntegerField(help_text='Links this file to its related customer document entry')),
                ('file_name', models.CharField(help_text='Original file name (e.g., policy_copy.pdf)', max_length=255)),
                ('file_path', models.CharField(help_text='Path or URL where the file is stored', max_length=500)),
                ('file_type', models.CharField(help_text='MIME type (e.g., application/pdf, image/jpeg)', max_length=100)),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of upload')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Status flag for active/inactive files')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who updated the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customer_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['customer_document_id', 'is_active'], name='customers_f_custome_1d1b1f_idx'), models.Index(fields=['uploaded_by', 'uploaded_at'], name='customers_f_uploade_34255f_idx'), models.Index(fields=['file_type', 'is_active'], name='customers_f_file_ty_5b9a44_idx')],
            },
        ),
    ]
