# Generated by Django 4.2.7 on 2025-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('customers_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who owns this file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_files', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='customerfile',
            index=models.Index(fields=['customer', 'is_active'], name='customers_f_custome_222606_idx'),
        ),
    ]
