# Generated by Django 4.2.7 on 2025-08-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_files', '0002_customerfile_customer_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerfile',
            name='customers_f_custome_1d1b1f_idx',
        ),
        migrations.RemoveField(
            model_name='customerfile',
            name='customer_document_id',
        ),
    ]
