# Generated by Django 4.2.7 on 2025-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_files', '0003_remove_customer_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfile',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original file name (e.g., policy_copy.pdf) - Auto-filled from uploaded file', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., application/pdf, image/jpeg) - Auto-detected from file', max_length=100, null=True),
        ),
    ]
