# Generated by Django 4.2.7 on 2025-10-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_files', '0005_make_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfile',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN number extracted from document (if applicable)', max_length=10, null=True),
        ),
    ]
