# Generated by Django 4.2.7 on 2025-11-04 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers_files', '0006_customerfile_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('income_proof', 'Income Proof'), ('business_registration', 'Business Registration'), ('tax_document', 'Tax Document'), ('bank_statement', 'Bank Statement'), ('medical_report', 'Medical Report'), ('photo', 'Photograph'), ('signature', 'Signature'), ('authorization', 'Authorization Letter'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card'), ('aadhar_card', 'Aadhar Card'), ('utility_bill', 'Utility Bill'), ('rental_agreement', 'Rental Agreement'), ('property_document', 'Property Document'), ('salary_slip', 'Salary Slip'), ('form_16', 'Form 16'), ('itr', 'Income Tax Return'), ('other', 'Other')], db_index=True, help_text='Type of document', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the document has been verified'),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when document was verified', null=True),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_customer_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customerfile',
            index=models.Index(fields=['document_type', 'is_verified'], name='customers_f_documen_a04f26_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfile',
            index=models.Index(fields=['is_verified'], name='customers_f_is_veri_b76198_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfile',
            index=models.Index(fields=['customer', 'is_verified'], name='customers_f_custome_0dd6b9_idx'),
        ),
        # Delete customers_documents table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS customers_documents CASCADE;",
            reverse_sql="-- Cannot reverse table deletion"
        ),
    ]
