# Generated by Django 5.2.7 on 2025-12-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_document_language_and_more'),
        ('feedback_and_surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_audience_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='category',
            field=models.CharField(choices=[('service_quality', 'Service Quality'), ('response_time', 'Response Time'), ('policy_info', 'Policy Information'), ('claims_process', 'Claims Process'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
