# Generated by Django 5.2.7 on 2025-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_surveys', '0002_remove_survey_is_active_survey_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='options',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='text',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='primary_color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
        migrations.AddField(
            model_name='survey',
            name='theme',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='label',
            field=models.CharField(blank=True, default='Question Label', max_length=500),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[('single_line', 'Single-line Text'), ('paragraph', 'Paragraph'), ('dropdown', 'Dropdown'), ('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('date_picker', 'Date Picker'), ('rating_scale', 'Rating Scale'), ('nps', 'Net Promoter Score'), ('section_break', 'Section Break'), ('matrix_grid', 'Matrix / Grid Question'), ('heading_text', 'Heading Text'), ('divider_line', 'Divider Line')], default='single_line', max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(default='Untitled Survey', max_length=255),
        ),
    ]
