# Generated by Django 5.2.7 on 2025-12-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience_manager', '0003_audiencecontact_expiry_date'),
        ('feedback_and_surveys', '0003_remove_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='primary_color',
        ),
        migrations.AddField(
            model_name='survey',
            name='audience',
            field=models.ForeignKey(blank=True, help_text='The specific group of users targeting for this survey.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='audience_manager.audience'),
        ),
    ]
