# Generated by Django 5.2.7 on 2025-12-31 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_surveys', '0004_remove_survey_primary_color_survey_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Internal name for this rule', max_length=200)),
                ('event_type', models.CharField(choices=[('policy_purchased', 'Policy Purchased'), ('claim_settled', 'Claim Settled'), ('ticket_closed', 'Support Ticket Closed'), ('renewal_completed', 'Renewal Completed')], max_length=50)),
                ('channels', models.JSONField(default=list, help_text="List of channels e.g. ['email', 'sms']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(help_text='Which survey to send?', on_delete=django.db.models.deletion.CASCADE, to='feedback_and_surveys.survey')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_automation_triggers',
            },
        ),
    ]
