# Generated by Django 5.2.7 on 2025-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_surveys', '0005_automationtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('csat', 'CSAT'), ('nps', 'NPS'), ('ces', 'CES'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
