# Generated by Django 5.2.7 on 2026-01-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_surveys', '0007_surveysubmission_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='category',
            field=models.CharField(choices=[('all_feedback', 'All Feedback'), ('unaddressed', 'Unaddressed'), ('negative/low_rating', 'Negative/Low Rating'), ('flagged_for_followup', 'Flagged For FollowUp'), ('with_attachments', 'With Attachements'), ('resolved_feedback', 'Resloved_Feedback'), ('service_quality', 'Service Quality')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('phone', 'Phone'), ('survey', 'Survey')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('unaddressed', 'Unaddressed'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='unaddressed', max_length=20),
        ),
    ]
