# Generated by Django 5.2.7 on 2026-01-02 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_surveys', '0008_alter_surveysubmission_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionactivitylog',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
