# Generated by Django 5.2.7 on 2026-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_surveys', '0010_automationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_event',
            field=models.CharField(choices=[('policy_purchase', 'Policy Purchase'), ('claim_settlement', 'Claim Settlement'), ('support_interaction', 'Support Interaction')], max_length=50),
        ),
    ]
