# Generated by Django 4.2.17 on 2025-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('show_edit_case_button', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'renewal_settings',
            },
        ),
    ]
