# Generated by Django 4.2.17 on 2026-01-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalsettings',
            name='enable_call_integration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='enforce_provider_limits',
            field=models.BooleanField(default=True),
        ),
    ]
