# Generated by Django 4.2.17 on 2026-01-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_provider', '0004_callproviderconfig_features'),
        ('renewal_settings', '0002_renewalsettings_enable_call_integration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renewalsettings',
            options={'verbose_name': 'Renewal Setting', 'verbose_name_plural': 'Renewal Settings'},
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='active_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_renewal_settings', to='call_provider.callproviderconfig'),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='default_call_duration',
            field=models.PositiveIntegerField(default=30, help_text='Default call duration in minutes'),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='enable_call_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='enable_call_recording',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='max_concurrent_calls',
            field=models.PositiveIntegerField(default=10, help_text='Maximum concurrent calls allowed'),
        ),
        migrations.AlterField(
            model_name='renewalsettings',
            name='enable_call_integration',
            field=models.BooleanField(default=False),
        ),
    ]
