# Generated by Django 4.2.17 on 2026-01-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_provider', '0005_remove_callproviderconfig_features'),
        ('renewal_settings', '0003_alter_renewalsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalsettings',
            name='active_provider',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_setting_profile', to='call_provider.callproviderconfig'),
            preserve_default=False,
        ),
    ]
