# Generated by Django 4.2.17 on 2026-01-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_provider', '0001_initial'),
        ('whatsapp_provider', '0025_alter_whatsappprovider_unique_together'),
        ('renewal_settings', '0004_alter_renewalsettings_active_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_quick_message_integration', models.BooleanField(default=False)),
                ('enable_delivery_reports', models.BooleanField(default=True)),
                ('enable_message_analytics', models.BooleanField(default=False)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Rate limit (messages/minute)')),
                ('daily_message_limit', models.PositiveIntegerField(default=1000, help_text='Daily message limit')),
                ('policy_renewal_reminder_template', models.TextField(default='Hi {{customerName}}, your {{policyType}} policy {{policyNumber}} is due for renewal on {{renewalDate}}. Please contact us to renew.', help_text='Template for Policy Renewal Reminder')),
                ('claim_status_update_template', models.TextField(default='Hello {{customerName}}, your claim {{claimNumber}} status has been updated to {{status}}. For queries, call us.', help_text='Template for Claim Status Update')),
                ('payment_confirmation_template', models.TextField(default='Thank you {{customerName}}! We have received your payment of {{amount}} for policy {{policyNumber}}. Receipt: {{receiptNumber}}', help_text='Template for Payment Confirmation')),
                ('active_sms_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_message_settings_active', to='sms_provider.smsprovider')),
                ('active_whatsapp_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_message_settings_active', to='whatsapp_provider.whatsappprovider')),
            ],
            options={
                'verbose_name': 'Quick Message Setting',
                'verbose_name_plural': 'Quick Message Settings',
                'db_table': 'quick_message_settings',
            },
        ),
    ]
