# Generated by Django 4.2.17 on 2026-01-06 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_settings', '0005_quickmessagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmessagesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickmessagesettings',
            name='is_active_configuration',
            field=models.BooleanField(default=True, help_text='Only one row should be active at a time.'),
        ),
    ]
