# Generated by Django 4.2.17 on 2026-01-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_settings', '0006_quickmessagesettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalsettings',
            name='auto_assign_cases',
            field=models.BooleanField(default=False, help_text='Automatically assign new cases to available agents'),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='default_renewal_period',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiry to start renewal process (Slider Value)'),
        ),
    ]
