# Generated by Django 4.2.17 on 2026-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_settings', '0007_renewalsettings_auto_assign_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmessagesettings',
            name='is_sms_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickmessagesettings',
            name='is_whatsapp_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='is_call_connected',
            field=models.BooleanField(default=False, help_text='True if the last integration test was successful'),
        ),
    ]
