# Generated by Django 4.2.17 on 2026-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_settings', '0008_quickmessagesettings_is_sms_connected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickmessagesettings',
            name='is_sms_connected',
        ),
        migrations.RemoveField(
            model_name='quickmessagesettings',
            name='is_whatsapp_connected',
        ),
        migrations.RemoveField(
            model_name='renewalsettings',
            name='is_call_connected',
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='is_call_integration_testing',
            field=models.BooleanField(default=False, help_text='Status of Call Integration Test'),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='is_sms_integration_testing',
            field=models.BooleanField(default=False, help_text='Status of SMS Integration Test'),
        ),
        migrations.AddField(
            model_name='renewalsettings',
            name='is_whatsapp_integration_testing',
            field=models.BooleanField(default=False, help_text='Status of WhatsApp Integration Test'),
        ),
    ]
