# Generated by Django 4.2.7 on 2025-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwebhook',
            name='event_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('blocked', 'Blocked'), ('deferred', 'Deferred'), ('dropped', 'Dropped'), ('incoming', 'Incoming Email')], max_length=20),
        ),
    ]
