# Generated by Django 4.2.7 on 2025-09-19 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email_integration', '0002_alter_emailwebhook_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sendgrid', 'SendGrid'), ('aws_ses', 'AWS SES'), ('mailgun', 'Mailgun'), ('postmark', 'Postmark')], max_length=20)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('blocked', 'Blocked'), ('deferred', 'Deferred'), ('dropped', 'Dropped'), ('incoming', 'Incoming Email')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('raw_data', models.JSONField(default=dict, help_text='Raw webhook payload')),
                ('processed_data', models.JSONField(blank=True, default=dict, help_text='Processed webhook data')),
                ('email_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Webhook',
                'verbose_name_plural': 'Email Webhooks',
                'db_table': 'email_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailwebhook',
            index=models.Index(fields=['provider', 'event_type'], name='email_webhooks_provider_event_idx'),
        ),
        migrations.AddIndex(
            model_name='emailwebhook',
            index=models.Index(fields=['status', 'created_at'], name='email_webhooks_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emailwebhook',
            index=models.Index(fields=['email_message_id', 'event_type'], name='email_webhooks_email_message_idx'),
        ),
    ]
