# Generated by Django 5.2.6 on 2025-09-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_integration', '0003_auto_20250919_1458'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailwebhook',
            new_name='email_webho_provide_60e6a6_idx',
            old_name='email_webhooks_provider_event_idx',
        ),
        migrations.RenameIndex(
            model_name='emailwebhook',
            new_name='email_webho_status_e54dd8_idx',
            old_name='email_webhooks_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='emailwebhook',
            new_name='email_webho_email_m_07215f_idx',
            old_name='email_webhooks_email_message_idx',
        ),
    ]
