# Generated by Django 5.2.7 on 2025-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_settings', '0002_flowaccessrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguration',
            name='enable_analytics_and_reports',
            field=models.BooleanField(default=True),
        ),
    ]
