# Generated by Django 5.2.7 on 2025-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_settings', '0003_whatsappconfiguration_enable_analytics_and_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguration',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='whatsappconfiguration',
            name='retry_delay',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
