# Generated by Django 5.2.7 on 2025-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_settings', '0004_whatsappconfiguration_max_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccesspermission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappconfiguration',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum retry attempts for failed flows'),
        ),
        migrations.AlterField(
            model_name='whatsappconfiguration',
            name='retry_delay',
            field=models.PositiveSmallIntegerField(default=300, help_text='Delay between retry attempts in seconds'),
        ),
    ]
