# Generated by Django 5.2.7 on 2025-12-15 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_flow_settings', '0005_whatsappaccesspermission_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccesspermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_flow_settings.flowaccessrole'),
        ),
        migrations.AlterField(
            model_name='whatsappaccesspermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_flow_permission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='whatsappaccesspermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user',), name='unique_active_permission'),
        ),
    ]
