# Generated by Django 4.2.7 on 2025-08-06 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, help_text="Customer's annual income", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('income_captured_date', models.DateField(blank=True, help_text='Date when income information was captured', null=True)),
                ('income_source', models.CharField(blank=True, choices=[('salary', 'Salary'), ('business', 'Business'), ('investment', 'Investment'), ('pension', 'Pension'), ('freelance', 'Freelance'), ('rental', 'Rental Income'), ('other', 'Other')], help_text="Primary source of customer's income", max_length=50)),
                ('policy_capacity_utilization', models.PositiveIntegerField(blank=True, help_text='Percentage of policy capacity currently utilized (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_policies_count', models.PositiveIntegerField(default=0, help_text='Number of policies recommended for this customer')),
                ('recommended_policies_value', models.PositiveIntegerField(default=0, help_text='Total value of recommended policies')),
                ('risk_profile', models.CharField(blank=True, choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive'), ('very_aggressive', 'Very Aggressive')], help_text="Customer's risk tolerance profile", max_length=20)),
                ('tolerance_score', models.DecimalField(blank=True, decimal_places=1, help_text='Risk tolerance score (0.0 to 10.0)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(help_text='Customer associated with this financial profile', on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_financial_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_fi_custome_e23069_idx'), models.Index(fields=['annual_income'], name='customer_fi_annual__3070dd_idx'), models.Index(fields=['risk_profile'], name='customer_fi_risk_pr_c53f6d_idx'), models.Index(fields=['income_captured_date'], name='customer_fi_income__3035d4_idx')],
            },
        ),
    ]
