# Generated by Django 5.2.7 on 2025-12-04 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_provider', '0001_initial'),
        ('sms_provider', '0001_initial'),
        ('whatsapp_provider', '0017_whatsappmessagetemplate_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_required', models.BooleanField(default=True, help_text='Require explicit consent before sending')),
                ('dnd_compliance', models.BooleanField(default=True, help_text='Check Do Not Disturb registry')),
                ('opt_in_required', models.BooleanField(default=True, help_text='Require users to opt-in for marketing')),
                ('data_retention_days', models.IntegerField(default=365, help_text='Days to retain campaign data')),
                ('email_rate_limit', models.IntegerField(default=1000, help_text='Emails per hour')),
                ('sms_rate_limit', models.IntegerField(default=100, help_text='SMS per hour')),
                ('whatsapp_rate_limit', models.IntegerField(default=80, help_text='WhatsApp messages per hour')),
                ('batch_size', models.IntegerField(default=50, help_text='Messages per batch')),
                ('retry_attempts', models.IntegerField(default=3, help_text='Failed message retry attempts')),
                ('template_approval_required', models.BooleanField(default=True, help_text='Require admin approval for new templates')),
                ('dlt_template_required', models.BooleanField(default=True, help_text='Require DLT template ID for SMS')),
                ('auto_save_templates', models.BooleanField(default=True, help_text='Automatically save drafts')),
                ('tracking_enabled', models.BooleanField(default=True, help_text='Enable open, click, and delivery tracking')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive events', max_length=500, null=True)),
                ('reporting_interval', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('email_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_settings_email', to='email_provider.emailproviderconfig')),
                ('sms_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_settings_sms', to='sms_provider.smsprovider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_settings', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_settings_whatsapp', to='whatsapp_provider.whatsappprovider')),
            ],
            options={
                'verbose_name': 'Campaign Setting',
                'verbose_name_plural': 'Campaign Settings',
                'db_table': 'campaign_settings',
            },
        ),
    ]
