# Generated by Django 5.2.7 on 2025-12-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsetting',
            name='export_format',
            field=models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel (XLSX)'), ('PDF', 'PDF Report'), ('JSON', 'JSON')], default='CSV', help_text='Preferred format for downloadable reports', max_length=10),
        ),
    ]
