# Generated by Django 5.2.7 on 2025-11-24 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience_manager', '0003_audiencecontact_expiry_date'),
        ('campaign_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for this provider', max_length=100)),
                ('provider_type', models.CharField(choices=[('twilio', 'Twilio SMS'), ('msg91', 'MSG91'), ('aws_sns', 'AWS SNS'), ('textlocal', 'TextLocal')], max_length=20)),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted API credentials for the provider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Use this provider by default for SMS')),
                ('is_active', models.BooleanField(default=True, help_text='Activate this provider')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=10, help_text='Max messages per minute')),
                ('daily_limit', models.PositiveIntegerField(default=1000)),
                ('monthly_limit', models.PositiveIntegerField(default=10000)),
                ('messages_sent_today', models.PositiveIntegerField(default=0)),
                ('messages_sent_total', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_providers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sms_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'db_table': 'sms_provider_type',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(help_text="Provider's unique message ID", max_length=255, unique=True)),
                ('to_phone_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('from_number', models.CharField(help_text='Sender number or ID', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='queued', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='campaign_manager.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='audience_manager.audiencecontact')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='sms_provider.smsprovider')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'db_table': 'sms_provider_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
